/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AgendamentoDashboardResponse from './model/AgendamentoDashboardResponse';
import AgendamentoPublicoReponse from './model/AgendamentoPublicoReponse';
import AgendamentoPublicoRequest from './model/AgendamentoPublicoRequest';
import AnamneseInicialRequest from './model/AnamneseInicialRequest';
import AnamneseInicialResponse from './model/AnamneseInicialResponse';
import AnamneseTecnicaRequest from './model/AnamneseTecnicaRequest';
import AnamneseTecnicaResponse from './model/AnamneseTecnicaResponse';
import AtendimentoDetalheResponse from './model/AtendimentoDetalheResponse';
import AtendimentoRelatorioResponse from './model/AtendimentoRelatorioResponse';
import ContadoresResponse from './model/ContadoresResponse';
import CreateUsuarioRequest from './model/CreateUsuarioRequest';
import EncaminhamentoOutrosResponse from './model/EncaminhamentoOutrosResponse';
import EncaminhamentoResponse from './model/EncaminhamentoResponse';
import EncaminhamentoTecnicoRequest from './model/EncaminhamentoTecnicoRequest';
import EncaminhamentoTecnicoResponse from './model/EncaminhamentoTecnicoResponse';
import FilaItemResponse from './model/FilaItemResponse';
import HorariosDisponiveisResponse from './model/HorariosDisponiveisResponse';
import KpiResponse from './model/KpiResponse';
import LgpdResponse from './model/LgpdResponse';
import LoginRequest from './model/LoginRequest';
import LoginResponse from './model/LoginResponse';
import MeResponse from './model/MeResponse';
import ObjetivoRequest from './model/ObjetivoRequest';
import ObjetivoResponse from './model/ObjetivoResponse';
import ObsJuridicaRequest from './model/ObsJuridicaRequest';
import ObsJuridicaResponse from './model/ObsJuridicaResponse';
import OrientacaoRequest from './model/OrientacaoRequest';
import OrientacaoResponse from './model/OrientacaoResponse';
import PacienteDetalheResponse from './model/PacienteDetalheResponse';
import PacienteSummaryResponse from './model/PacienteSummaryResponse';
import ProntuarioRequest from './model/ProntuarioRequest';
import ProntuarioResponse from './model/ProntuarioResponse';
import RefreshRequest from './model/RefreshRequest';
import RefreshResponse from './model/RefreshResponse';
import TimelineEventoResponse from './model/TimelineEventoResponse';
import UpdateUsuarioRequest from './model/UpdateUsuarioRequest';
import UsuarioResponse from './model/UsuarioResponse';
import UsuarioSummaryResponse from './model/UsuarioSummaryResponse';
import ViolenciaRequest from './model/ViolenciaRequest';
import ViolenciaResponse from './model/ViolenciaResponse';
import VolumeDiarioResponse from './model/VolumeDiarioResponse';
import AgendamentoPublicoApi from './api/AgendamentoPublicoApi';
import AnamneseInicialApi from './api/AnamneseInicialApi';
import AnamneseTecnicaApi from './api/AnamneseTecnicaApi';
import AuthApi from './api/AuthApi';
import DashboardApi from './api/DashboardApi';
import EncaminhamentosApi from './api/EncaminhamentosApi';
import FilasApi from './api/FilasApi';
import ObservacaoJuridicaApi from './api/ObservacaoJuridicaApi';
import PDFApi from './api/PDFApi';
import PacientesApi from './api/PacientesApi';
import ProntuarioPsicossocialApi from './api/ProntuarioPsicossocialApi';
import RelatoriosApi from './api/RelatoriosApi';
import UsuariosApi from './api/UsuariosApi';


/**
* Sistema de atendimento Sala Lilás.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SalaLilsApi = require('index'); // See note below*.
* var xxxSvc = new SalaLilsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SalaLilsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SalaLilsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SalaLilsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AgendamentoDashboardResponse model constructor.
     * @property {module:model/AgendamentoDashboardResponse}
     */
    AgendamentoDashboardResponse,

    /**
     * The AgendamentoPublicoReponse model constructor.
     * @property {module:model/AgendamentoPublicoReponse}
     */
    AgendamentoPublicoReponse,

    /**
     * The AgendamentoPublicoRequest model constructor.
     * @property {module:model/AgendamentoPublicoRequest}
     */
    AgendamentoPublicoRequest,

    /**
     * The AnamneseInicialRequest model constructor.
     * @property {module:model/AnamneseInicialRequest}
     */
    AnamneseInicialRequest,

    /**
     * The AnamneseInicialResponse model constructor.
     * @property {module:model/AnamneseInicialResponse}
     */
    AnamneseInicialResponse,

    /**
     * The AnamneseTecnicaRequest model constructor.
     * @property {module:model/AnamneseTecnicaRequest}
     */
    AnamneseTecnicaRequest,

    /**
     * The AnamneseTecnicaResponse model constructor.
     * @property {module:model/AnamneseTecnicaResponse}
     */
    AnamneseTecnicaResponse,

    /**
     * The AtendimentoDetalheResponse model constructor.
     * @property {module:model/AtendimentoDetalheResponse}
     */
    AtendimentoDetalheResponse,

    /**
     * The AtendimentoRelatorioResponse model constructor.
     * @property {module:model/AtendimentoRelatorioResponse}
     */
    AtendimentoRelatorioResponse,

    /**
     * The ContadoresResponse model constructor.
     * @property {module:model/ContadoresResponse}
     */
    ContadoresResponse,

    /**
     * The CreateUsuarioRequest model constructor.
     * @property {module:model/CreateUsuarioRequest}
     */
    CreateUsuarioRequest,

    /**
     * The EncaminhamentoOutrosResponse model constructor.
     * @property {module:model/EncaminhamentoOutrosResponse}
     */
    EncaminhamentoOutrosResponse,

    /**
     * The EncaminhamentoResponse model constructor.
     * @property {module:model/EncaminhamentoResponse}
     */
    EncaminhamentoResponse,

    /**
     * The EncaminhamentoTecnicoRequest model constructor.
     * @property {module:model/EncaminhamentoTecnicoRequest}
     */
    EncaminhamentoTecnicoRequest,

    /**
     * The EncaminhamentoTecnicoResponse model constructor.
     * @property {module:model/EncaminhamentoTecnicoResponse}
     */
    EncaminhamentoTecnicoResponse,

    /**
     * The FilaItemResponse model constructor.
     * @property {module:model/FilaItemResponse}
     */
    FilaItemResponse,

    /**
     * The HorariosDisponiveisResponse model constructor.
     * @property {module:model/HorariosDisponiveisResponse}
     */
    HorariosDisponiveisResponse,

    /**
     * The KpiResponse model constructor.
     * @property {module:model/KpiResponse}
     */
    KpiResponse,

    /**
     * The LgpdResponse model constructor.
     * @property {module:model/LgpdResponse}
     */
    LgpdResponse,

    /**
     * The LoginRequest model constructor.
     * @property {module:model/LoginRequest}
     */
    LoginRequest,

    /**
     * The LoginResponse model constructor.
     * @property {module:model/LoginResponse}
     */
    LoginResponse,

    /**
     * The MeResponse model constructor.
     * @property {module:model/MeResponse}
     */
    MeResponse,

    /**
     * The ObjetivoRequest model constructor.
     * @property {module:model/ObjetivoRequest}
     */
    ObjetivoRequest,

    /**
     * The ObjetivoResponse model constructor.
     * @property {module:model/ObjetivoResponse}
     */
    ObjetivoResponse,

    /**
     * The ObsJuridicaRequest model constructor.
     * @property {module:model/ObsJuridicaRequest}
     */
    ObsJuridicaRequest,

    /**
     * The ObsJuridicaResponse model constructor.
     * @property {module:model/ObsJuridicaResponse}
     */
    ObsJuridicaResponse,

    /**
     * The OrientacaoRequest model constructor.
     * @property {module:model/OrientacaoRequest}
     */
    OrientacaoRequest,

    /**
     * The OrientacaoResponse model constructor.
     * @property {module:model/OrientacaoResponse}
     */
    OrientacaoResponse,

    /**
     * The PacienteDetalheResponse model constructor.
     * @property {module:model/PacienteDetalheResponse}
     */
    PacienteDetalheResponse,

    /**
     * The PacienteSummaryResponse model constructor.
     * @property {module:model/PacienteSummaryResponse}
     */
    PacienteSummaryResponse,

    /**
     * The ProntuarioRequest model constructor.
     * @property {module:model/ProntuarioRequest}
     */
    ProntuarioRequest,

    /**
     * The ProntuarioResponse model constructor.
     * @property {module:model/ProntuarioResponse}
     */
    ProntuarioResponse,

    /**
     * The RefreshRequest model constructor.
     * @property {module:model/RefreshRequest}
     */
    RefreshRequest,

    /**
     * The RefreshResponse model constructor.
     * @property {module:model/RefreshResponse}
     */
    RefreshResponse,

    /**
     * The TimelineEventoResponse model constructor.
     * @property {module:model/TimelineEventoResponse}
     */
    TimelineEventoResponse,

    /**
     * The UpdateUsuarioRequest model constructor.
     * @property {module:model/UpdateUsuarioRequest}
     */
    UpdateUsuarioRequest,

    /**
     * The UsuarioResponse model constructor.
     * @property {module:model/UsuarioResponse}
     */
    UsuarioResponse,

    /**
     * The UsuarioSummaryResponse model constructor.
     * @property {module:model/UsuarioSummaryResponse}
     */
    UsuarioSummaryResponse,

    /**
     * The ViolenciaRequest model constructor.
     * @property {module:model/ViolenciaRequest}
     */
    ViolenciaRequest,

    /**
     * The ViolenciaResponse model constructor.
     * @property {module:model/ViolenciaResponse}
     */
    ViolenciaResponse,

    /**
     * The VolumeDiarioResponse model constructor.
     * @property {module:model/VolumeDiarioResponse}
     */
    VolumeDiarioResponse,

    /**
    * The AgendamentoPublicoApi service constructor.
    * @property {module:api/AgendamentoPublicoApi}
    */
    AgendamentoPublicoApi,

    /**
    * The AnamneseInicialApi service constructor.
    * @property {module:api/AnamneseInicialApi}
    */
    AnamneseInicialApi,

    /**
    * The AnamneseTecnicaApi service constructor.
    * @property {module:api/AnamneseTecnicaApi}
    */
    AnamneseTecnicaApi,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The DashboardApi service constructor.
    * @property {module:api/DashboardApi}
    */
    DashboardApi,

    /**
    * The EncaminhamentosApi service constructor.
    * @property {module:api/EncaminhamentosApi}
    */
    EncaminhamentosApi,

    /**
    * The FilasApi service constructor.
    * @property {module:api/FilasApi}
    */
    FilasApi,

    /**
    * The ObservacaoJuridicaApi service constructor.
    * @property {module:api/ObservacaoJuridicaApi}
    */
    ObservacaoJuridicaApi,

    /**
    * The PDFApi service constructor.
    * @property {module:api/PDFApi}
    */
    PDFApi,

    /**
    * The PacientesApi service constructor.
    * @property {module:api/PacientesApi}
    */
    PacientesApi,

    /**
    * The ProntuarioPsicossocialApi service constructor.
    * @property {module:api/ProntuarioPsicossocialApi}
    */
    ProntuarioPsicossocialApi,

    /**
    * The RelatoriosApi service constructor.
    * @property {module:api/RelatoriosApi}
    */
    RelatoriosApi,

    /**
    * The UsuariosApi service constructor.
    * @property {module:api/UsuariosApi}
    */
    UsuariosApi
};
