/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AgendamentoPublicoReponse from '../model/AgendamentoPublicoReponse';
import AgendamentoPublicoRequest from '../model/AgendamentoPublicoRequest';
import HorariosDisponiveisResponse from '../model/HorariosDisponiveisResponse';

/**
* AgendamentoPublico service.
* @module api/AgendamentoPublicoApi
* @version 1.0.0
*/
export default class AgendamentoPublicoApi {

    /**
    * Constructs a new AgendamentoPublicoApi. 
    * @alias module:api/AgendamentoPublicoApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Cria um novo agendamento externo
     * @param {module:model/AgendamentoPublicoRequest} agendamentoPublicoRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AgendamentoPublicoReponse} and HTTP response
     */
    criar5WithHttpInfo(agendamentoPublicoRequest) {
      let postBody = agendamentoPublicoRequest;
      // verify the required parameter 'agendamentoPublicoRequest' is set
      if (agendamentoPublicoRequest === undefined || agendamentoPublicoRequest === null) {
        throw new Error("Missing the required parameter 'agendamentoPublicoRequest' when calling criar5");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = AgendamentoPublicoReponse;
      return this.apiClient.callApi(
        '/agendamentos/publico', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Cria um novo agendamento externo
     * @param {module:model/AgendamentoPublicoRequest} agendamentoPublicoRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AgendamentoPublicoReponse}
     */
    criar5(agendamentoPublicoRequest) {
      return this.criar5WithHttpInfo(agendamentoPublicoRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Lista horários disponíveis para uma data
     * @param {Date} data 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/HorariosDisponiveisResponse} and HTTP response
     */
    horariosWithHttpInfo(data) {
      let postBody = null;
      // verify the required parameter 'data' is set
      if (data === undefined || data === null) {
        throw new Error("Missing the required parameter 'data' when calling horarios");
      }

      let pathParams = {
      };
      let queryParams = {
        'data': data
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = HorariosDisponiveisResponse;
      return this.apiClient.callApi(
        '/agendamentos/publico/horarios', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Lista horários disponíveis para uma data
     * @param {Date} data 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/HorariosDisponiveisResponse}
     */
    horarios(data) {
      return this.horariosWithHttpInfo(data)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
