/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AnamneseInicialRequest from '../model/AnamneseInicialRequest';
import AnamneseInicialResponse from '../model/AnamneseInicialResponse';

/**
* AnamneseInicial service.
* @module api/AnamneseInicialApi
* @version 1.0.0
*/
export default class AnamneseInicialApi {

    /**
    * Constructs a new AnamneseInicialApi. 
    * @alias module:api/AnamneseInicialApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Atualiza anamnese inicial - somente enquanto status = TRIAGEM
     * @param {String} agendamentoId 
     * @param {module:model/AnamneseInicialRequest} anamneseInicialRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnamneseInicialResponse} and HTTP response
     */
    atualizar4WithHttpInfo(agendamentoId, anamneseInicialRequest) {
      let postBody = anamneseInicialRequest;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling atualizar4");
      }
      // verify the required parameter 'anamneseInicialRequest' is set
      if (anamneseInicialRequest === undefined || anamneseInicialRequest === null) {
        throw new Error("Missing the required parameter 'anamneseInicialRequest' when calling atualizar4");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = AnamneseInicialResponse;
      return this.apiClient.callApi(
        '/anamnese-inicial/{agendamentoId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Atualiza anamnese inicial - somente enquanto status = TRIAGEM
     * @param {String} agendamentoId 
     * @param {module:model/AnamneseInicialRequest} anamneseInicialRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnamneseInicialResponse}
     */
    atualizar4(agendamentoId, anamneseInicialRequest) {
      return this.atualizar4WithHttpInfo(agendamentoId, anamneseInicialRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Busca anamnese inicial de um atendimento
     * @param {String} agendamentoId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnamneseInicialResponse} and HTTP response
     */
    buscar4WithHttpInfo(agendamentoId) {
      let postBody = null;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling buscar4");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AnamneseInicialResponse;
      return this.apiClient.callApi(
        '/anamnese-inicial/{agendamentoId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Busca anamnese inicial de um atendimento
     * @param {String} agendamentoId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnamneseInicialResponse}
     */
    buscar4(agendamentoId) {
      return this.buscar4WithHttpInfo(agendamentoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Cria anamnese inicial - somente Atendente, status deve ser TRIAGEM
     * @param {String} agendamentoId 
     * @param {module:model/AnamneseInicialRequest} anamneseInicialRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnamneseInicialResponse} and HTTP response
     */
    criar3WithHttpInfo(agendamentoId, anamneseInicialRequest) {
      let postBody = anamneseInicialRequest;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling criar3");
      }
      // verify the required parameter 'anamneseInicialRequest' is set
      if (anamneseInicialRequest === undefined || anamneseInicialRequest === null) {
        throw new Error("Missing the required parameter 'anamneseInicialRequest' when calling criar3");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = AnamneseInicialResponse;
      return this.apiClient.callApi(
        '/anamnese-inicial/{agendamentoId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Cria anamnese inicial - somente Atendente, status deve ser TRIAGEM
     * @param {String} agendamentoId 
     * @param {module:model/AnamneseInicialRequest} anamneseInicialRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnamneseInicialResponse}
     */
    criar3(agendamentoId, anamneseInicialRequest) {
      return this.criar3WithHttpInfo(agendamentoId, anamneseInicialRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
