/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AnamneseTecnicaRequest from '../model/AnamneseTecnicaRequest';
import AnamneseTecnicaResponse from '../model/AnamneseTecnicaResponse';

/**
* AnamneseTecnica service.
* @module api/AnamneseTecnicaApi
* @version 1.0.0
*/
export default class AnamneseTecnicaApi {

    /**
    * Constructs a new AnamneseTecnicaApi. 
    * @alias module:api/AnamneseTecnicaApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Atualiza anamnese técnica - somente quando status = TECNICA
     * @param {String} agendamentoId 
     * @param {module:model/AnamneseTecnicaRequest} anamneseTecnicaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnamneseTecnicaResponse} and HTTP response
     */
    atualizar3WithHttpInfo(agendamentoId, anamneseTecnicaRequest) {
      let postBody = anamneseTecnicaRequest;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling atualizar3");
      }
      // verify the required parameter 'anamneseTecnicaRequest' is set
      if (anamneseTecnicaRequest === undefined || anamneseTecnicaRequest === null) {
        throw new Error("Missing the required parameter 'anamneseTecnicaRequest' when calling atualizar3");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = AnamneseTecnicaResponse;
      return this.apiClient.callApi(
        '/anamnese-tecnica/{agendamentoId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Atualiza anamnese técnica - somente quando status = TECNICA
     * @param {String} agendamentoId 
     * @param {module:model/AnamneseTecnicaRequest} anamneseTecnicaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnamneseTecnicaResponse}
     */
    atualizar3(agendamentoId, anamneseTecnicaRequest) {
      return this.atualizar3WithHttpInfo(agendamentoId, anamneseTecnicaRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Busca anamnese técnica - ATENDENTE recebe 403
     * @param {String} agendamentoId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnamneseTecnicaResponse} and HTTP response
     */
    buscar3WithHttpInfo(agendamentoId) {
      let postBody = null;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling buscar3");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AnamneseTecnicaResponse;
      return this.apiClient.callApi(
        '/anamnese-tecnica/{agendamentoId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Busca anamnese técnica - ATENDENTE recebe 403
     * @param {String} agendamentoId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnamneseTecnicaResponse}
     */
    buscar3(agendamentoId) {
      return this.buscar3WithHttpInfo(agendamentoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Cria anamnese técnica - somente equipe Técnica, status deve ser TECNICA
     * @param {String} agendamentoId 
     * @param {module:model/AnamneseTecnicaRequest} anamneseTecnicaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AnamneseTecnicaResponse} and HTTP response
     */
    criar2WithHttpInfo(agendamentoId, anamneseTecnicaRequest) {
      let postBody = anamneseTecnicaRequest;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling criar2");
      }
      // verify the required parameter 'anamneseTecnicaRequest' is set
      if (anamneseTecnicaRequest === undefined || anamneseTecnicaRequest === null) {
        throw new Error("Missing the required parameter 'anamneseTecnicaRequest' when calling criar2");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = AnamneseTecnicaResponse;
      return this.apiClient.callApi(
        '/anamnese-tecnica/{agendamentoId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Cria anamnese técnica - somente equipe Técnica, status deve ser TECNICA
     * @param {String} agendamentoId 
     * @param {module:model/AnamneseTecnicaRequest} anamneseTecnicaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AnamneseTecnicaResponse}
     */
    criar2(agendamentoId, anamneseTecnicaRequest) {
      return this.criar2WithHttpInfo(agendamentoId, anamneseTecnicaRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
