/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AgendamentoDashboardResponse from '../model/AgendamentoDashboardResponse';
import ContadoresResponse from '../model/ContadoresResponse';

/**
* Dashboard service.
* @module api/DashboardApi
* @version 1.0.0
*/
export default class DashboardApi {

    /**
    * Constructs a new DashboardApi. 
    * @alias module:api/DashboardApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Check-in do paciente - altera status para TRIAGEM
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AgendamentoDashboardResponse} and HTTP response
     */
    checkinWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling checkin");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AgendamentoDashboardResponse;
      return this.apiClient.callApi(
        '/dashboard/agendamentos/{id}/checkin', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Check-in do paciente - altera status para TRIAGEM
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AgendamentoDashboardResponse}
     */
    checkin(id) {
      return this.checkinWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retorna contadores da fila do dia
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ContadoresResponse} and HTTP response
     */
    contadoresWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ContadoresResponse;
      return this.apiClient.callApi(
        '/dashboard/contadores', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retorna contadores da fila do dia
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ContadoresResponse}
     */
    contadores() {
      return this.contadoresWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Lista agendamentos do dia com status AGENDADO
     * @param {Object} opts Optional parameters
     * @param {Date} [data] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/AgendamentoDashboardResponse>} and HTTP response
     */
    listar2WithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'data': opts['data']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [AgendamentoDashboardResponse];
      return this.apiClient.callApi(
        '/dashboard/agendamentos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Lista agendamentos do dia com status AGENDADO
     * @param {Object} opts Optional parameters
     * @param {Date} opts.data 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/AgendamentoDashboardResponse>}
     */
    listar2(opts) {
      return this.listar2WithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Marca paciente como ausense - finaliza atendimento (irreversível)
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AgendamentoDashboardResponse} and HTTP response
     */
    naoVeioWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling naoVeio");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = AgendamentoDashboardResponse;
      return this.apiClient.callApi(
        '/dashboard/agendamentos/{id}/nao-veio', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Marca paciente como ausense - finaliza atendimento (irreversível)
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AgendamentoDashboardResponse}
     */
    naoVeio(id) {
      return this.naoVeioWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
