/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import FilaItemResponse from '../model/FilaItemResponse';

/**
* Filas service.
* @module api/FilasApi
* @version 1.0.0
*/
export default class FilasApi {

    /**
    * Constructs a new FilasApi. 
    * @alias module:api/FilasApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Fila do NPJ — atendimentos com status JURIDICO
     * @param {Object} opts Optional parameters
     * @param {Date} [data] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/FilaItemResponse>} and HTTP response
     */
    filaJuridicoWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'data': opts['data']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [FilaItemResponse];
      return this.apiClient.callApi(
        '/filas/juridico', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Fila do NPJ — atendimentos com status JURIDICO
     * @param {Object} opts Optional parameters
     * @param {Date} opts.data 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/FilaItemResponse>}
     */
    filaJuridico(opts) {
      return this.filaJuridicoWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fila do CIS — atendimentos com status PSICOLOGIA
     * @param {Object} opts Optional parameters
     * @param {Date} [data] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/FilaItemResponse>} and HTTP response
     */
    filaPsicologiaWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'data': opts['data']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [FilaItemResponse];
      return this.apiClient.callApi(
        '/filas/psicologia', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Fila do CIS — atendimentos com status PSICOLOGIA
     * @param {Object} opts Optional parameters
     * @param {Date} opts.data 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/FilaItemResponse>}
     */
    filaPsicologia(opts) {
      return this.filaPsicologiaWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Fila da Equipe Técnica — atendimentos com status TECNICA
     * @param {Object} opts Optional parameters
     * @param {Date} [data] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/FilaItemResponse>} and HTTP response
     */
    filaTecnicaWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'data': opts['data']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [FilaItemResponse];
      return this.apiClient.callApi(
        '/filas/tecnica', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Fila da Equipe Técnica — atendimentos com status TECNICA
     * @param {Object} opts Optional parameters
     * @param {Date} opts.data 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/FilaItemResponse>}
     */
    filaTecnica(opts) {
      return this.filaTecnicaWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
