/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ObsJuridicaRequest from '../model/ObsJuridicaRequest';
import ObsJuridicaResponse from '../model/ObsJuridicaResponse';

/**
* ObservacaoJuridica service.
* @module api/ObservacaoJuridicaApi
* @version 1.0.0
*/
export default class ObservacaoJuridicaApi {

    /**
    * Constructs a new ObservacaoJuridicaApi. 
    * @alias module:api/ObservacaoJuridicaApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Atualiza observação jurídica — somente enquanto status = JURIDICO
     * @param {String} agendamentoId 
     * @param {module:model/ObsJuridicaRequest} obsJuridicaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ObsJuridicaResponse} and HTTP response
     */
    atualizar2WithHttpInfo(agendamentoId, obsJuridicaRequest) {
      let postBody = obsJuridicaRequest;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling atualizar2");
      }
      // verify the required parameter 'obsJuridicaRequest' is set
      if (obsJuridicaRequest === undefined || obsJuridicaRequest === null) {
        throw new Error("Missing the required parameter 'obsJuridicaRequest' when calling atualizar2");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = ObsJuridicaResponse;
      return this.apiClient.callApi(
        '/obs-juridicas/{agendamentoId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Atualiza observação jurídica — somente enquanto status = JURIDICO
     * @param {String} agendamentoId 
     * @param {module:model/ObsJuridicaRequest} obsJuridicaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ObsJuridicaResponse}
     */
    atualizar2(agendamentoId, obsJuridicaRequest) {
      return this.atualizar2WithHttpInfo(agendamentoId, obsJuridicaRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Busca observação jurídica de um atendimento
     * @param {String} agendamentoId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ObsJuridicaResponse} and HTTP response
     */
    buscar2WithHttpInfo(agendamentoId) {
      let postBody = null;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling buscar2");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ObsJuridicaResponse;
      return this.apiClient.callApi(
        '/obs-juridicas/{agendamentoId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Busca observação jurídica de um atendimento
     * @param {String} agendamentoId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ObsJuridicaResponse}
     */
    buscar2(agendamentoId) {
      return this.buscar2WithHttpInfo(agendamentoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Cria observação jurídica — somente NPJ, status deve ser JURIDICO
     * @param {String} agendamentoId 
     * @param {module:model/ObsJuridicaRequest} obsJuridicaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ObsJuridicaResponse} and HTTP response
     */
    criar1WithHttpInfo(agendamentoId, obsJuridicaRequest) {
      let postBody = obsJuridicaRequest;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling criar1");
      }
      // verify the required parameter 'obsJuridicaRequest' is set
      if (obsJuridicaRequest === undefined || obsJuridicaRequest === null) {
        throw new Error("Missing the required parameter 'obsJuridicaRequest' when calling criar1");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = ObsJuridicaResponse;
      return this.apiClient.callApi(
        '/obs-juridicas/{agendamentoId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Cria observação jurídica — somente NPJ, status deve ser JURIDICO
     * @param {String} agendamentoId 
     * @param {module:model/ObsJuridicaRequest} obsJuridicaRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ObsJuridicaResponse}
     */
    criar1(agendamentoId, obsJuridicaRequest) {
      return this.criar1WithHttpInfo(agendamentoId, obsJuridicaRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
