/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PacienteDetalheResponse from '../model/PacienteDetalheResponse';
import PacienteSummaryResponse from '../model/PacienteSummaryResponse';
import TimelineEventoResponse from '../model/TimelineEventoResponse';

/**
* Pacientes service.
* @module api/PacientesApi
* @version 1.0.0
*/
export default class PacientesApi {

    /**
    * Constructs a new PacientesApi. 
    * @alias module:api/PacientesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Retorna dados completos do paciente com todos os atendiemntos
     * @param {String} pacienteId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PacienteDetalheResponse} and HTTP response
     */
    buscar5WithHttpInfo(pacienteId) {
      let postBody = null;
      // verify the required parameter 'pacienteId' is set
      if (pacienteId === undefined || pacienteId === null) {
        throw new Error("Missing the required parameter 'pacienteId' when calling buscar5");
      }

      let pathParams = {
        'pacienteId': pacienteId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PacienteDetalheResponse;
      return this.apiClient.callApi(
        '/pacientes/{pacienteId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retorna dados completos do paciente com todos os atendiemntos
     * @param {String} pacienteId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PacienteDetalheResponse}
     */
    buscar5(pacienteId) {
      return this.buscar5WithHttpInfo(pacienteId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Lista todos os pacientes com histórico no sistema
     * @param {Object} opts Optional parameters
     * @param {String} [busca] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/PacienteSummaryResponse>} and HTTP response
     */
    listar1WithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'busca': opts['busca']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [PacienteSummaryResponse];
      return this.apiClient.callApi(
        '/pacientes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Lista todos os pacientes com histórico no sistema
     * @param {Object} opts Optional parameters
     * @param {String} opts.busca 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/PacienteSummaryResponse>}
     */
    listar1(opts) {
      return this.listar1WithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retorna timeline cronológica completa do paciente
     * @param {String} pacienteId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/TimelineEventoResponse>} and HTTP response
     */
    timelineWithHttpInfo(pacienteId) {
      let postBody = null;
      // verify the required parameter 'pacienteId' is set
      if (pacienteId === undefined || pacienteId === null) {
        throw new Error("Missing the required parameter 'pacienteId' when calling timeline");
      }

      let pathParams = {
        'pacienteId': pacienteId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [TimelineEventoResponse];
      return this.apiClient.callApi(
        '/pacientes/{pacienteId}/timeline', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retorna timeline cronológica completa do paciente
     * @param {String} pacienteId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/TimelineEventoResponse>}
     */
    timeline(pacienteId) {
      return this.timelineWithHttpInfo(pacienteId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
