/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* PDF service.
* @module api/PDFApi
* @version 1.0.0
*/
export default class PDFApi {

    /**
    * Constructs a new PDFApi. 
    * @alias module:api/PDFApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Gera ou baixa o PDF consolidade do atendimento
     * @param {String} agendamentoId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Blob} and HTTP response
     */
    downloadWithHttpInfo(agendamentoId) {
      let postBody = null;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling download");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'Blob';
      return this.apiClient.callApi(
        '/pdf/{agendamentoId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Gera ou baixa o PDF consolidade do atendimento
     * @param {String} agendamentoId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Blob}
     */
    download(agendamentoId) {
      return this.downloadWithHttpInfo(agendamentoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
