/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ProntuarioRequest from '../model/ProntuarioRequest';
import ProntuarioResponse from '../model/ProntuarioResponse';

/**
* ProntuarioPsicossocial service.
* @module api/ProntuarioPsicossocialApi
* @version 1.0.0
*/
export default class ProntuarioPsicossocialApi {

    /**
    * Constructs a new ProntuarioPsicossocialApi. 
    * @alias module:api/ProntuarioPsicossocialApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Atualiza prontuário - somente enquanto status = PSICOLOGIA
     * @param {String} agendamentoId 
     * @param {module:model/ProntuarioRequest} prontuarioRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ProntuarioResponse} and HTTP response
     */
    atualizar1WithHttpInfo(agendamentoId, prontuarioRequest) {
      let postBody = prontuarioRequest;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling atualizar1");
      }
      // verify the required parameter 'prontuarioRequest' is set
      if (prontuarioRequest === undefined || prontuarioRequest === null) {
        throw new Error("Missing the required parameter 'prontuarioRequest' when calling atualizar1");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = ProntuarioResponse;
      return this.apiClient.callApi(
        '/prontuarios/{agendamentoId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Atualiza prontuário - somente enquanto status = PSICOLOGIA
     * @param {String} agendamentoId 
     * @param {module:model/ProntuarioRequest} prontuarioRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ProntuarioResponse}
     */
    atualizar1(agendamentoId, prontuarioRequest) {
      return this.atualizar1WithHttpInfo(agendamentoId, prontuarioRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Busca prontuário psicossocial de um atendimento
     * @param {String} agendamentoId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ProntuarioResponse} and HTTP response
     */
    buscar1WithHttpInfo(agendamentoId) {
      let postBody = null;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling buscar1");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ProntuarioResponse;
      return this.apiClient.callApi(
        '/prontuarios/{agendamentoId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Busca prontuário psicossocial de um atendimento
     * @param {String} agendamentoId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ProntuarioResponse}
     */
    buscar1(agendamentoId) {
      return this.buscar1WithHttpInfo(agendamentoId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Cria prontuário - somente CIS, status deve ser PSICOLOGIA
     * @param {String} agendamentoId 
     * @param {module:model/ProntuarioRequest} prontuarioRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ProntuarioResponse} and HTTP response
     */
    criarWithHttpInfo(agendamentoId, prontuarioRequest) {
      let postBody = prontuarioRequest;
      // verify the required parameter 'agendamentoId' is set
      if (agendamentoId === undefined || agendamentoId === null) {
        throw new Error("Missing the required parameter 'agendamentoId' when calling criar");
      }
      // verify the required parameter 'prontuarioRequest' is set
      if (prontuarioRequest === undefined || prontuarioRequest === null) {
        throw new Error("Missing the required parameter 'prontuarioRequest' when calling criar");
      }

      let pathParams = {
        'agendamentoId': agendamentoId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = ProntuarioResponse;
      return this.apiClient.callApi(
        '/prontuarios/{agendamentoId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Cria prontuário - somente CIS, status deve ser PSICOLOGIA
     * @param {String} agendamentoId 
     * @param {module:model/ProntuarioRequest} prontuarioRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ProntuarioResponse}
     */
    criar(agendamentoId, prontuarioRequest) {
      return this.criarWithHttpInfo(agendamentoId, prontuarioRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
