/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AtendimentoRelatorioResponse from '../model/AtendimentoRelatorioResponse';
import KpiResponse from '../model/KpiResponse';
import VolumeDiarioResponse from '../model/VolumeDiarioResponse';

/**
* Relatorios service.
* @module api/RelatoriosApi
* @version 1.0.0
*/
export default class RelatoriosApi {

    /**
    * Constructs a new RelatoriosApi. 
    * @alias module:api/RelatoriosApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Lista detalhada de atendimentos no período
     * @param {Object} opts Optional parameters
     * @param {Date} [dataInico] 
     * @param {Date} [dataFim] 
     * @param {String} [status] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/AtendimentoRelatorioResponse>} and HTTP response
     */
    atendimentosWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'dataInico': opts['dataInico'],
        'dataFim': opts['dataFim'],
        'status': opts['status']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [AtendimentoRelatorioResponse];
      return this.apiClient.callApi(
        '/relatorios/atendimentos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Lista detalhada de atendimentos no período
     * @param {Object} opts Optional parameters
     * @param {Date} opts.dataInico 
     * @param {Date} opts.dataFim 
     * @param {String} opts.status 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/AtendimentoRelatorioResponse>}
     */
    atendimentos(opts) {
      return this.atendimentosWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * KPIS gerais - total de atendimentos, por status e por dia
     * @param {Object} opts Optional parameters
     * @param {Date} [dataInicio] 
     * @param {Date} [dataFim] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/KpiResponse} and HTTP response
     */
    kpisWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'dataInicio': opts['dataInicio'],
        'dataFim': opts['dataFim']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = KpiResponse;
      return this.apiClient.callApi(
        '/relatorios/kpis', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * KPIS gerais - total de atendimentos, por status e por dia
     * @param {Object} opts Optional parameters
     * @param {Date} opts.dataInicio 
     * @param {Date} opts.dataFim 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/KpiResponse}
     */
    kpis(opts) {
      return this.kpisWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Volume de atendimentos agrupado por dia
     * @param {Object} opts Optional parameters
     * @param {Date} [dataInico] 
     * @param {Date} [dataFim] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/VolumeDiarioResponse>} and HTTP response
     */
    volumeDiarioWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'dataInico': opts['dataInico'],
        'dataFim': opts['dataFim']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [VolumeDiarioResponse];
      return this.apiClient.callApi(
        '/relatorios/volume-diario', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Volume de atendimentos agrupado por dia
     * @param {Object} opts Optional parameters
     * @param {Date} opts.dataInico 
     * @param {Date} opts.dataFim 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/VolumeDiarioResponse>}
     */
    volumeDiario(opts) {
      return this.volumeDiarioWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
