/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateUsuarioRequest from '../model/CreateUsuarioRequest';
import UpdateUsuarioRequest from '../model/UpdateUsuarioRequest';
import UsuarioResponse from '../model/UsuarioResponse';
import UsuarioSummaryResponse from '../model/UsuarioSummaryResponse';

/**
* Usuarios service.
* @module api/UsuariosApi
* @version 1.0.0
*/
export default class UsuariosApi {

    /**
    * Constructs a new UsuariosApi. 
    * @alias module:api/UsuariosApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Atualiza dados e perfil de um usuário
     * @param {String} id 
     * @param {module:model/UpdateUsuarioRequest} updateUsuarioRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UsuarioResponse} and HTTP response
     */
    atualizarWithHttpInfo(id, updateUsuarioRequest) {
      let postBody = updateUsuarioRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling atualizar");
      }
      // verify the required parameter 'updateUsuarioRequest' is set
      if (updateUsuarioRequest === undefined || updateUsuarioRequest === null) {
        throw new Error("Missing the required parameter 'updateUsuarioRequest' when calling atualizar");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = UsuarioResponse;
      return this.apiClient.callApi(
        '/usuarios/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Atualiza dados e perfil de um usuário
     * @param {String} id 
     * @param {module:model/UpdateUsuarioRequest} updateUsuarioRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UsuarioResponse}
     */
    atualizar(id, updateUsuarioRequest) {
      return this.atualizarWithHttpInfo(id, updateUsuarioRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retorna dados completos de um usuário
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UsuarioResponse} and HTTP response
     */
    buscarWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling buscar");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = UsuarioResponse;
      return this.apiClient.callApi(
        '/usuarios/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retorna dados completos de um usuário
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UsuarioResponse}
     */
    buscar(id) {
      return this.buscarWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Cria novo usuário interno
     * @param {module:model/CreateUsuarioRequest} createUsuarioRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UsuarioResponse} and HTTP response
     */
    criar4WithHttpInfo(createUsuarioRequest) {
      let postBody = createUsuarioRequest;
      // verify the required parameter 'createUsuarioRequest' is set
      if (createUsuarioRequest === undefined || createUsuarioRequest === null) {
        throw new Error("Missing the required parameter 'createUsuarioRequest' when calling criar4");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = UsuarioResponse;
      return this.apiClient.callApi(
        '/usuarios', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Cria novo usuário interno
     * @param {module:model/CreateUsuarioRequest} createUsuarioRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UsuarioResponse}
     */
    criar4(createUsuarioRequest) {
      return this.criar4WithHttpInfo(createUsuarioRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Desativa o acesso do usuário (soft delete)
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    desativarWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling desativar");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/usuarios/{id}/desativar', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Desativa o acesso do usuário (soft delete)
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    desativar(id) {
      return this.desativarWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Lista de todos os colaboradores
     * @param {Object} opts Optional parameters
     * @param {String} [busca] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/UsuarioSummaryResponse>} and HTTP response
     */
    listarWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'busca': opts['busca']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [UsuarioSummaryResponse];
      return this.apiClient.callApi(
        '/usuarios', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Lista de todos os colaboradores
     * @param {Object} opts Optional parameters
     * @param {String} opts.busca 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/UsuarioSummaryResponse>}
     */
    listar(opts) {
      return this.listarWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Reativa um usuário previamente desativado
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    reativarWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling reativar");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/usuarios/{id}/reativar', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Reativa um usuário previamente desativado
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    reativar(id) {
      return this.reativarWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
