/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalaLilsApi);
  }
}(this, function(expect, SalaLilsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalaLilsApi.EncaminhamentosApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EncaminhamentosApi', function() {
    describe('finalizar', function() {
      it('should call finalizar successfully', function(done) {
        //uncomment below and update the code to test finalizar
        //instance.finalizar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paraJuridico', function() {
      it('should call paraJuridico successfully', function(done) {
        //uncomment below and update the code to test paraJuridico
        //instance.paraJuridico(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paraOutros', function() {
      it('should call paraOutros successfully', function(done) {
        //uncomment below and update the code to test paraOutros
        //instance.paraOutros(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paraPsicologia', function() {
      it('should call paraPsicologia successfully', function(done) {
        //uncomment below and update the code to test paraPsicologia
        //instance.paraPsicologia(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('paraTecnica', function() {
      it('should call paraTecnica successfully', function(done) {
        //uncomment below and update the code to test paraTecnica
        //instance.paraTecnica(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
