/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AgendamentoPublicoRequest model module.
 * @module model/AgendamentoPublicoRequest
 * @version 1.0.0
 */
class AgendamentoPublicoRequest {
    /**
     * Constructs a new <code>AgendamentoPublicoRequest</code>.
     * @alias module:model/AgendamentoPublicoRequest
     * @param nome {String} 
     * @param email {String} 
     * @param cpf {String} 
     * @param data {Date} 
     * @param horario {String} 
     */
    constructor(nome, email, cpf, data, horario) { 
        
        AgendamentoPublicoRequest.initialize(this, nome, email, cpf, data, horario);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nome, email, cpf, data, horario) { 
        obj['nome'] = nome;
        obj['email'] = email;
        obj['cpf'] = cpf;
        obj['data'] = data;
        obj['horario'] = horario;
    }

    /**
     * Constructs a <code>AgendamentoPublicoRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AgendamentoPublicoRequest} obj Optional instance to populate.
     * @return {module:model/AgendamentoPublicoRequest} The populated <code>AgendamentoPublicoRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AgendamentoPublicoRequest();

            if (data.hasOwnProperty('nome')) {
                obj['nome'] = ApiClient.convertToType(data['nome'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('cpf')) {
                obj['cpf'] = ApiClient.convertToType(data['cpf'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'Date');
            }
            if (data.hasOwnProperty('horario')) {
                obj['horario'] = ApiClient.convertToType(data['horario'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AgendamentoPublicoRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AgendamentoPublicoRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AgendamentoPublicoRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['nome'] && !(typeof data['nome'] === 'string' || data['nome'] instanceof String)) {
            throw new Error("Expected the field `nome` to be a primitive type in the JSON string but got " + data['nome']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['cpf'] && !(typeof data['cpf'] === 'string' || data['cpf'] instanceof String)) {
            throw new Error("Expected the field `cpf` to be a primitive type in the JSON string but got " + data['cpf']);
        }
        // ensure the json data is a string
        if (data['horario'] && !(typeof data['horario'] === 'string' || data['horario'] instanceof String)) {
            throw new Error("Expected the field `horario` to be a primitive type in the JSON string but got " + data['horario']);
        }

        return true;
    }


}

AgendamentoPublicoRequest.RequiredProperties = ["nome", "email", "cpf", "data", "horario"];

/**
 * @member {String} nome
 */
AgendamentoPublicoRequest.prototype['nome'] = undefined;

/**
 * @member {String} email
 */
AgendamentoPublicoRequest.prototype['email'] = undefined;

/**
 * @member {String} cpf
 */
AgendamentoPublicoRequest.prototype['cpf'] = undefined;

/**
 * @member {Date} data
 */
AgendamentoPublicoRequest.prototype['data'] = undefined;

/**
 * @member {String} horario
 */
AgendamentoPublicoRequest.prototype['horario'] = undefined;






export default AgendamentoPublicoRequest;

