/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AgendamentoPublicoReponse model module.
 * @module model/AgendamentoPublicoReponse
 * @version 1.0.0
 */
class AgendamentoPublicoReponse {
    /**
     * Constructs a new <code>AgendamentoPublicoReponse</code>.
     * @alias module:model/AgendamentoPublicoReponse
     */
    constructor() { 
        
        AgendamentoPublicoReponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AgendamentoPublicoReponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AgendamentoPublicoReponse} obj Optional instance to populate.
     * @return {module:model/AgendamentoPublicoReponse} The populated <code>AgendamentoPublicoReponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AgendamentoPublicoReponse();

            if (data.hasOwnProperty('agendamentoId')) {
                obj['agendamentoId'] = ApiClient.convertToType(data['agendamentoId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AgendamentoPublicoReponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AgendamentoPublicoReponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['agendamentoId'] && !(typeof data['agendamentoId'] === 'string' || data['agendamentoId'] instanceof String)) {
            throw new Error("Expected the field `agendamentoId` to be a primitive type in the JSON string but got " + data['agendamentoId']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {String} agendamentoId
 */
AgendamentoPublicoReponse.prototype['agendamentoId'] = undefined;

/**
 * @member {String} status
 */
AgendamentoPublicoReponse.prototype['status'] = undefined;






export default AgendamentoPublicoReponse;

