/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EncaminhamentoTecnicoResponse from './EncaminhamentoTecnicoResponse';
import ObjetivoResponse from './ObjetivoResponse';
import OrientacaoResponse from './OrientacaoResponse';

/**
 * The AnamneseTecnicaResponse model module.
 * @module model/AnamneseTecnicaResponse
 * @version 1.0.0
 */
class AnamneseTecnicaResponse {
    /**
     * Constructs a new <code>AnamneseTecnicaResponse</code>.
     * @alias module:model/AnamneseTecnicaResponse
     */
    constructor() { 
        
        AnamneseTecnicaResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AnamneseTecnicaResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnamneseTecnicaResponse} obj Optional instance to populate.
     * @return {module:model/AnamneseTecnicaResponse} The populated <code>AnamneseTecnicaResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnamneseTecnicaResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('agendamentoId')) {
                obj['agendamentoId'] = ApiClient.convertToType(data['agendamentoId'], 'String');
            }
            if (data.hasOwnProperty('pacienteNome')) {
                obj['pacienteNome'] = ApiClient.convertToType(data['pacienteNome'], 'String');
            }
            if (data.hasOwnProperty('riscoIminente')) {
                obj['riscoIminente'] = ApiClient.convertToType(data['riscoIminente'], 'Boolean');
            }
            if (data.hasOwnProperty('agressorConvive')) {
                obj['agressorConvive'] = ApiClient.convertToType(data['agressorConvive'], 'Boolean');
            }
            if (data.hasOwnProperty('historicoViolencia')) {
                obj['historicoViolencia'] = ApiClient.convertToType(data['historicoViolencia'], 'Boolean');
            }
            if (data.hasOwnProperty('redeApoio')) {
                obj['redeApoio'] = ApiClient.convertToType(data['redeApoio'], 'Boolean');
            }
            if (data.hasOwnProperty('filhosDependentes')) {
                obj['filhosDependentes'] = ApiClient.convertToType(data['filhosDependentes'], 'Boolean');
            }
            if (data.hasOwnProperty('observacoes')) {
                obj['observacoes'] = ApiClient.convertToType(data['observacoes'], 'String');
            }
            if (data.hasOwnProperty('registroAtendimento')) {
                obj['registroAtendimento'] = ApiClient.convertToType(data['registroAtendimento'], 'String');
            }
            if (data.hasOwnProperty('detalhamentoEncaminhamentos')) {
                obj['detalhamentoEncaminhamentos'] = ApiClient.convertToType(data['detalhamentoEncaminhamentos'], 'String');
            }
            if (data.hasOwnProperty('planoAcompanhamento')) {
                obj['planoAcompanhamento'] = ApiClient.convertToType(data['planoAcompanhamento'], 'String');
            }
            if (data.hasOwnProperty('dataRetorno')) {
                obj['dataRetorno'] = ApiClient.convertToType(data['dataRetorno'], 'Date');
            }
            if (data.hasOwnProperty('planoObservacoes')) {
                obj['planoObservacoes'] = ApiClient.convertToType(data['planoObservacoes'], 'String');
            }
            if (data.hasOwnProperty('sinteseCaso')) {
                obj['sinteseCaso'] = ApiClient.convertToType(data['sinteseCaso'], 'String');
            }
            if (data.hasOwnProperty('orientacoes')) {
                obj['orientacoes'] = ApiClient.convertToType(data['orientacoes'], [OrientacaoResponse]);
            }
            if (data.hasOwnProperty('encaminhamentos')) {
                obj['encaminhamentos'] = ApiClient.convertToType(data['encaminhamentos'], [EncaminhamentoTecnicoResponse]);
            }
            if (data.hasOwnProperty('objetivos')) {
                obj['objetivos'] = ApiClient.convertToType(data['objetivos'], [ObjetivoResponse]);
            }
            if (data.hasOwnProperty('criadoEm')) {
                obj['criadoEm'] = ApiClient.convertToType(data['criadoEm'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnamneseTecnicaResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnamneseTecnicaResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['agendamentoId'] && !(typeof data['agendamentoId'] === 'string' || data['agendamentoId'] instanceof String)) {
            throw new Error("Expected the field `agendamentoId` to be a primitive type in the JSON string but got " + data['agendamentoId']);
        }
        // ensure the json data is a string
        if (data['pacienteNome'] && !(typeof data['pacienteNome'] === 'string' || data['pacienteNome'] instanceof String)) {
            throw new Error("Expected the field `pacienteNome` to be a primitive type in the JSON string but got " + data['pacienteNome']);
        }
        // ensure the json data is a string
        if (data['observacoes'] && !(typeof data['observacoes'] === 'string' || data['observacoes'] instanceof String)) {
            throw new Error("Expected the field `observacoes` to be a primitive type in the JSON string but got " + data['observacoes']);
        }
        // ensure the json data is a string
        if (data['registroAtendimento'] && !(typeof data['registroAtendimento'] === 'string' || data['registroAtendimento'] instanceof String)) {
            throw new Error("Expected the field `registroAtendimento` to be a primitive type in the JSON string but got " + data['registroAtendimento']);
        }
        // ensure the json data is a string
        if (data['detalhamentoEncaminhamentos'] && !(typeof data['detalhamentoEncaminhamentos'] === 'string' || data['detalhamentoEncaminhamentos'] instanceof String)) {
            throw new Error("Expected the field `detalhamentoEncaminhamentos` to be a primitive type in the JSON string but got " + data['detalhamentoEncaminhamentos']);
        }
        // ensure the json data is a string
        if (data['planoAcompanhamento'] && !(typeof data['planoAcompanhamento'] === 'string' || data['planoAcompanhamento'] instanceof String)) {
            throw new Error("Expected the field `planoAcompanhamento` to be a primitive type in the JSON string but got " + data['planoAcompanhamento']);
        }
        // ensure the json data is a string
        if (data['planoObservacoes'] && !(typeof data['planoObservacoes'] === 'string' || data['planoObservacoes'] instanceof String)) {
            throw new Error("Expected the field `planoObservacoes` to be a primitive type in the JSON string but got " + data['planoObservacoes']);
        }
        // ensure the json data is a string
        if (data['sinteseCaso'] && !(typeof data['sinteseCaso'] === 'string' || data['sinteseCaso'] instanceof String)) {
            throw new Error("Expected the field `sinteseCaso` to be a primitive type in the JSON string but got " + data['sinteseCaso']);
        }
        if (data['orientacoes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['orientacoes'])) {
                throw new Error("Expected the field `orientacoes` to be an array in the JSON data but got " + data['orientacoes']);
            }
            // validate the optional field `orientacoes` (array)
            for (const item of data['orientacoes']) {
                OrientacaoResponse.validateJSON(item);
            };
        }
        if (data['encaminhamentos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['encaminhamentos'])) {
                throw new Error("Expected the field `encaminhamentos` to be an array in the JSON data but got " + data['encaminhamentos']);
            }
            // validate the optional field `encaminhamentos` (array)
            for (const item of data['encaminhamentos']) {
                EncaminhamentoTecnicoResponse.validateJSON(item);
            };
        }
        if (data['objetivos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['objetivos'])) {
                throw new Error("Expected the field `objetivos` to be an array in the JSON data but got " + data['objetivos']);
            }
            // validate the optional field `objetivos` (array)
            for (const item of data['objetivos']) {
                ObjetivoResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} id
 */
AnamneseTecnicaResponse.prototype['id'] = undefined;

/**
 * @member {String} agendamentoId
 */
AnamneseTecnicaResponse.prototype['agendamentoId'] = undefined;

/**
 * @member {String} pacienteNome
 */
AnamneseTecnicaResponse.prototype['pacienteNome'] = undefined;

/**
 * @member {Boolean} riscoIminente
 */
AnamneseTecnicaResponse.prototype['riscoIminente'] = undefined;

/**
 * @member {Boolean} agressorConvive
 */
AnamneseTecnicaResponse.prototype['agressorConvive'] = undefined;

/**
 * @member {Boolean} historicoViolencia
 */
AnamneseTecnicaResponse.prototype['historicoViolencia'] = undefined;

/**
 * @member {Boolean} redeApoio
 */
AnamneseTecnicaResponse.prototype['redeApoio'] = undefined;

/**
 * @member {Boolean} filhosDependentes
 */
AnamneseTecnicaResponse.prototype['filhosDependentes'] = undefined;

/**
 * @member {String} observacoes
 */
AnamneseTecnicaResponse.prototype['observacoes'] = undefined;

/**
 * @member {String} registroAtendimento
 */
AnamneseTecnicaResponse.prototype['registroAtendimento'] = undefined;

/**
 * @member {String} detalhamentoEncaminhamentos
 */
AnamneseTecnicaResponse.prototype['detalhamentoEncaminhamentos'] = undefined;

/**
 * @member {String} planoAcompanhamento
 */
AnamneseTecnicaResponse.prototype['planoAcompanhamento'] = undefined;

/**
 * @member {Date} dataRetorno
 */
AnamneseTecnicaResponse.prototype['dataRetorno'] = undefined;

/**
 * @member {String} planoObservacoes
 */
AnamneseTecnicaResponse.prototype['planoObservacoes'] = undefined;

/**
 * @member {String} sinteseCaso
 */
AnamneseTecnicaResponse.prototype['sinteseCaso'] = undefined;

/**
 * @member {Array.<module:model/OrientacaoResponse>} orientacoes
 */
AnamneseTecnicaResponse.prototype['orientacoes'] = undefined;

/**
 * @member {Array.<module:model/EncaminhamentoTecnicoResponse>} encaminhamentos
 */
AnamneseTecnicaResponse.prototype['encaminhamentos'] = undefined;

/**
 * @member {Array.<module:model/ObjetivoResponse>} objetivos
 */
AnamneseTecnicaResponse.prototype['objetivos'] = undefined;

/**
 * @member {Date} criadoEm
 */
AnamneseTecnicaResponse.prototype['criadoEm'] = undefined;






export default AnamneseTecnicaResponse;

