/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EncaminhamentoTecnicoRequest from './EncaminhamentoTecnicoRequest';
import ObjetivoRequest from './ObjetivoRequest';
import OrientacaoRequest from './OrientacaoRequest';

/**
 * The AnamneseTecnicaRequest model module.
 * @module model/AnamneseTecnicaRequest
 * @version 1.0.0
 */
class AnamneseTecnicaRequest {
    /**
     * Constructs a new <code>AnamneseTecnicaRequest</code>.
     * @alias module:model/AnamneseTecnicaRequest
     * @param riscoIminente {Boolean} 
     * @param agressorConvive {Boolean} 
     * @param historicoViolencia {Boolean} 
     * @param redeApoio {Boolean} 
     * @param filhosDependentes {Boolean} 
     * @param planoAcompanhamento {String} 
     */
    constructor(riscoIminente, agressorConvive, historicoViolencia, redeApoio, filhosDependentes, planoAcompanhamento) { 
        
        AnamneseTecnicaRequest.initialize(this, riscoIminente, agressorConvive, historicoViolencia, redeApoio, filhosDependentes, planoAcompanhamento);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, riscoIminente, agressorConvive, historicoViolencia, redeApoio, filhosDependentes, planoAcompanhamento) { 
        obj['riscoIminente'] = riscoIminente;
        obj['agressorConvive'] = agressorConvive;
        obj['historicoViolencia'] = historicoViolencia;
        obj['redeApoio'] = redeApoio;
        obj['filhosDependentes'] = filhosDependentes;
        obj['planoAcompanhamento'] = planoAcompanhamento;
    }

    /**
     * Constructs a <code>AnamneseTecnicaRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnamneseTecnicaRequest} obj Optional instance to populate.
     * @return {module:model/AnamneseTecnicaRequest} The populated <code>AnamneseTecnicaRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnamneseTecnicaRequest();

            if (data.hasOwnProperty('riscoIminente')) {
                obj['riscoIminente'] = ApiClient.convertToType(data['riscoIminente'], 'Boolean');
            }
            if (data.hasOwnProperty('agressorConvive')) {
                obj['agressorConvive'] = ApiClient.convertToType(data['agressorConvive'], 'Boolean');
            }
            if (data.hasOwnProperty('historicoViolencia')) {
                obj['historicoViolencia'] = ApiClient.convertToType(data['historicoViolencia'], 'Boolean');
            }
            if (data.hasOwnProperty('redeApoio')) {
                obj['redeApoio'] = ApiClient.convertToType(data['redeApoio'], 'Boolean');
            }
            if (data.hasOwnProperty('filhosDependentes')) {
                obj['filhosDependentes'] = ApiClient.convertToType(data['filhosDependentes'], 'Boolean');
            }
            if (data.hasOwnProperty('observacoes')) {
                obj['observacoes'] = ApiClient.convertToType(data['observacoes'], 'String');
            }
            if (data.hasOwnProperty('registroAtendimento')) {
                obj['registroAtendimento'] = ApiClient.convertToType(data['registroAtendimento'], 'String');
            }
            if (data.hasOwnProperty('detalhamentoEncaminhamentos')) {
                obj['detalhamentoEncaminhamentos'] = ApiClient.convertToType(data['detalhamentoEncaminhamentos'], 'String');
            }
            if (data.hasOwnProperty('planoAcompanhamento')) {
                obj['planoAcompanhamento'] = ApiClient.convertToType(data['planoAcompanhamento'], 'String');
            }
            if (data.hasOwnProperty('dataRetorno')) {
                obj['dataRetorno'] = ApiClient.convertToType(data['dataRetorno'], 'Date');
            }
            if (data.hasOwnProperty('planoObservacoes')) {
                obj['planoObservacoes'] = ApiClient.convertToType(data['planoObservacoes'], 'String');
            }
            if (data.hasOwnProperty('sinteseCaso')) {
                obj['sinteseCaso'] = ApiClient.convertToType(data['sinteseCaso'], 'String');
            }
            if (data.hasOwnProperty('orientacoes')) {
                obj['orientacoes'] = ApiClient.convertToType(data['orientacoes'], [OrientacaoRequest]);
            }
            if (data.hasOwnProperty('encaminhamentos')) {
                obj['encaminhamentos'] = ApiClient.convertToType(data['encaminhamentos'], [EncaminhamentoTecnicoRequest]);
            }
            if (data.hasOwnProperty('objetivos')) {
                obj['objetivos'] = ApiClient.convertToType(data['objetivos'], [ObjetivoRequest]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnamneseTecnicaRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnamneseTecnicaRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AnamneseTecnicaRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['observacoes'] && !(typeof data['observacoes'] === 'string' || data['observacoes'] instanceof String)) {
            throw new Error("Expected the field `observacoes` to be a primitive type in the JSON string but got " + data['observacoes']);
        }
        // ensure the json data is a string
        if (data['registroAtendimento'] && !(typeof data['registroAtendimento'] === 'string' || data['registroAtendimento'] instanceof String)) {
            throw new Error("Expected the field `registroAtendimento` to be a primitive type in the JSON string but got " + data['registroAtendimento']);
        }
        // ensure the json data is a string
        if (data['detalhamentoEncaminhamentos'] && !(typeof data['detalhamentoEncaminhamentos'] === 'string' || data['detalhamentoEncaminhamentos'] instanceof String)) {
            throw new Error("Expected the field `detalhamentoEncaminhamentos` to be a primitive type in the JSON string but got " + data['detalhamentoEncaminhamentos']);
        }
        // ensure the json data is a string
        if (data['planoAcompanhamento'] && !(typeof data['planoAcompanhamento'] === 'string' || data['planoAcompanhamento'] instanceof String)) {
            throw new Error("Expected the field `planoAcompanhamento` to be a primitive type in the JSON string but got " + data['planoAcompanhamento']);
        }
        // ensure the json data is a string
        if (data['planoObservacoes'] && !(typeof data['planoObservacoes'] === 'string' || data['planoObservacoes'] instanceof String)) {
            throw new Error("Expected the field `planoObservacoes` to be a primitive type in the JSON string but got " + data['planoObservacoes']);
        }
        // ensure the json data is a string
        if (data['sinteseCaso'] && !(typeof data['sinteseCaso'] === 'string' || data['sinteseCaso'] instanceof String)) {
            throw new Error("Expected the field `sinteseCaso` to be a primitive type in the JSON string but got " + data['sinteseCaso']);
        }
        if (data['orientacoes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['orientacoes'])) {
                throw new Error("Expected the field `orientacoes` to be an array in the JSON data but got " + data['orientacoes']);
            }
            // validate the optional field `orientacoes` (array)
            for (const item of data['orientacoes']) {
                OrientacaoRequest.validateJSON(item);
            };
        }
        if (data['encaminhamentos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['encaminhamentos'])) {
                throw new Error("Expected the field `encaminhamentos` to be an array in the JSON data but got " + data['encaminhamentos']);
            }
            // validate the optional field `encaminhamentos` (array)
            for (const item of data['encaminhamentos']) {
                EncaminhamentoTecnicoRequest.validateJSON(item);
            };
        }
        if (data['objetivos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['objetivos'])) {
                throw new Error("Expected the field `objetivos` to be an array in the JSON data but got " + data['objetivos']);
            }
            // validate the optional field `objetivos` (array)
            for (const item of data['objetivos']) {
                ObjetivoRequest.validateJSON(item);
            };
        }

        return true;
    }


}

AnamneseTecnicaRequest.RequiredProperties = ["riscoIminente", "agressorConvive", "historicoViolencia", "redeApoio", "filhosDependentes", "planoAcompanhamento"];

/**
 * @member {Boolean} riscoIminente
 */
AnamneseTecnicaRequest.prototype['riscoIminente'] = undefined;

/**
 * @member {Boolean} agressorConvive
 */
AnamneseTecnicaRequest.prototype['agressorConvive'] = undefined;

/**
 * @member {Boolean} historicoViolencia
 */
AnamneseTecnicaRequest.prototype['historicoViolencia'] = undefined;

/**
 * @member {Boolean} redeApoio
 */
AnamneseTecnicaRequest.prototype['redeApoio'] = undefined;

/**
 * @member {Boolean} filhosDependentes
 */
AnamneseTecnicaRequest.prototype['filhosDependentes'] = undefined;

/**
 * @member {String} observacoes
 */
AnamneseTecnicaRequest.prototype['observacoes'] = undefined;

/**
 * @member {String} registroAtendimento
 */
AnamneseTecnicaRequest.prototype['registroAtendimento'] = undefined;

/**
 * @member {String} detalhamentoEncaminhamentos
 */
AnamneseTecnicaRequest.prototype['detalhamentoEncaminhamentos'] = undefined;

/**
 * @member {String} planoAcompanhamento
 */
AnamneseTecnicaRequest.prototype['planoAcompanhamento'] = undefined;

/**
 * @member {Date} dataRetorno
 */
AnamneseTecnicaRequest.prototype['dataRetorno'] = undefined;

/**
 * @member {String} planoObservacoes
 */
AnamneseTecnicaRequest.prototype['planoObservacoes'] = undefined;

/**
 * @member {String} sinteseCaso
 */
AnamneseTecnicaRequest.prototype['sinteseCaso'] = undefined;

/**
 * @member {Array.<module:model/OrientacaoRequest>} orientacoes
 */
AnamneseTecnicaRequest.prototype['orientacoes'] = undefined;

/**
 * @member {Array.<module:model/EncaminhamentoTecnicoRequest>} encaminhamentos
 */
AnamneseTecnicaRequest.prototype['encaminhamentos'] = undefined;

/**
 * @member {Array.<module:model/ObjetivoRequest>} objetivos
 */
AnamneseTecnicaRequest.prototype['objetivos'] = undefined;






export default AnamneseTecnicaRequest;

