/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ViolenciaResponse from './ViolenciaResponse';

/**
 * The AnamneseInicialResponse model module.
 * @module model/AnamneseInicialResponse
 * @version 1.0.0
 */
class AnamneseInicialResponse {
    /**
     * Constructs a new <code>AnamneseInicialResponse</code>.
     * @alias module:model/AnamneseInicialResponse
     */
    constructor() { 
        
        AnamneseInicialResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AnamneseInicialResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnamneseInicialResponse} obj Optional instance to populate.
     * @return {module:model/AnamneseInicialResponse} The populated <code>AnamneseInicialResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnamneseInicialResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('agendamentoId')) {
                obj['agendamentoId'] = ApiClient.convertToType(data['agendamentoId'], 'String');
            }
            if (data.hasOwnProperty('pacienteNome')) {
                obj['pacienteNome'] = ApiClient.convertToType(data['pacienteNome'], 'String');
            }
            if (data.hasOwnProperty('dataAtendimento')) {
                obj['dataAtendimento'] = ApiClient.convertToType(data['dataAtendimento'], 'Date');
            }
            if (data.hasOwnProperty('horario')) {
                obj['horario'] = ApiClient.convertToType(data['horario'], 'String');
            }
            if (data.hasOwnProperty('tipoAtendimento')) {
                obj['tipoAtendimento'] = ApiClient.convertToType(data['tipoAtendimento'], 'String');
            }
            if (data.hasOwnProperty('primeiroAtendimento')) {
                obj['primeiroAtendimento'] = ApiClient.convertToType(data['primeiroAtendimento'], 'Boolean');
            }
            if (data.hasOwnProperty('territorio')) {
                obj['territorio'] = ApiClient.convertToType(data['territorio'], 'String');
            }
            if (data.hasOwnProperty('corRaca')) {
                obj['corRaca'] = ApiClient.convertToType(data['corRaca'], 'String');
            }
            if (data.hasOwnProperty('sexoGenero')) {
                obj['sexoGenero'] = ApiClient.convertToType(data['sexoGenero'], 'String');
            }
            if (data.hasOwnProperty('sexoGeneroOutro')) {
                obj['sexoGeneroOutro'] = ApiClient.convertToType(data['sexoGeneroOutro'], 'String');
            }
            if (data.hasOwnProperty('violencias')) {
                obj['violencias'] = ApiClient.convertToType(data['violencias'], [ViolenciaResponse]);
            }
            if (data.hasOwnProperty('criadoEm')) {
                obj['criadoEm'] = ApiClient.convertToType(data['criadoEm'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnamneseInicialResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnamneseInicialResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['agendamentoId'] && !(typeof data['agendamentoId'] === 'string' || data['agendamentoId'] instanceof String)) {
            throw new Error("Expected the field `agendamentoId` to be a primitive type in the JSON string but got " + data['agendamentoId']);
        }
        // ensure the json data is a string
        if (data['pacienteNome'] && !(typeof data['pacienteNome'] === 'string' || data['pacienteNome'] instanceof String)) {
            throw new Error("Expected the field `pacienteNome` to be a primitive type in the JSON string but got " + data['pacienteNome']);
        }
        // ensure the json data is a string
        if (data['horario'] && !(typeof data['horario'] === 'string' || data['horario'] instanceof String)) {
            throw new Error("Expected the field `horario` to be a primitive type in the JSON string but got " + data['horario']);
        }
        // ensure the json data is a string
        if (data['tipoAtendimento'] && !(typeof data['tipoAtendimento'] === 'string' || data['tipoAtendimento'] instanceof String)) {
            throw new Error("Expected the field `tipoAtendimento` to be a primitive type in the JSON string but got " + data['tipoAtendimento']);
        }
        // ensure the json data is a string
        if (data['territorio'] && !(typeof data['territorio'] === 'string' || data['territorio'] instanceof String)) {
            throw new Error("Expected the field `territorio` to be a primitive type in the JSON string but got " + data['territorio']);
        }
        // ensure the json data is a string
        if (data['corRaca'] && !(typeof data['corRaca'] === 'string' || data['corRaca'] instanceof String)) {
            throw new Error("Expected the field `corRaca` to be a primitive type in the JSON string but got " + data['corRaca']);
        }
        // ensure the json data is a string
        if (data['sexoGenero'] && !(typeof data['sexoGenero'] === 'string' || data['sexoGenero'] instanceof String)) {
            throw new Error("Expected the field `sexoGenero` to be a primitive type in the JSON string but got " + data['sexoGenero']);
        }
        // ensure the json data is a string
        if (data['sexoGeneroOutro'] && !(typeof data['sexoGeneroOutro'] === 'string' || data['sexoGeneroOutro'] instanceof String)) {
            throw new Error("Expected the field `sexoGeneroOutro` to be a primitive type in the JSON string but got " + data['sexoGeneroOutro']);
        }
        if (data['violencias']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['violencias'])) {
                throw new Error("Expected the field `violencias` to be an array in the JSON data but got " + data['violencias']);
            }
            // validate the optional field `violencias` (array)
            for (const item of data['violencias']) {
                ViolenciaResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} id
 */
AnamneseInicialResponse.prototype['id'] = undefined;

/**
 * @member {String} agendamentoId
 */
AnamneseInicialResponse.prototype['agendamentoId'] = undefined;

/**
 * @member {String} pacienteNome
 */
AnamneseInicialResponse.prototype['pacienteNome'] = undefined;

/**
 * @member {Date} dataAtendimento
 */
AnamneseInicialResponse.prototype['dataAtendimento'] = undefined;

/**
 * @member {String} horario
 */
AnamneseInicialResponse.prototype['horario'] = undefined;

/**
 * @member {String} tipoAtendimento
 */
AnamneseInicialResponse.prototype['tipoAtendimento'] = undefined;

/**
 * @member {Boolean} primeiroAtendimento
 */
AnamneseInicialResponse.prototype['primeiroAtendimento'] = undefined;

/**
 * @member {String} territorio
 */
AnamneseInicialResponse.prototype['territorio'] = undefined;

/**
 * @member {String} corRaca
 */
AnamneseInicialResponse.prototype['corRaca'] = undefined;

/**
 * @member {String} sexoGenero
 */
AnamneseInicialResponse.prototype['sexoGenero'] = undefined;

/**
 * @member {String} sexoGeneroOutro
 */
AnamneseInicialResponse.prototype['sexoGeneroOutro'] = undefined;

/**
 * @member {Array.<module:model/ViolenciaResponse>} violencias
 */
AnamneseInicialResponse.prototype['violencias'] = undefined;

/**
 * @member {Date} criadoEm
 */
AnamneseInicialResponse.prototype['criadoEm'] = undefined;






export default AnamneseInicialResponse;

