/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ViolenciaRequest from './ViolenciaRequest';

/**
 * The AnamneseInicialRequest model module.
 * @module model/AnamneseInicialRequest
 * @version 1.0.0
 */
class AnamneseInicialRequest {
    /**
     * Constructs a new <code>AnamneseInicialRequest</code>.
     * @alias module:model/AnamneseInicialRequest
     * @param tipoAtendimento {String} 
     * @param primeiroAtendimento {Boolean} 
     * @param corRaca {String} 
     * @param sexoGenero {String} 
     * @param violencias {Array.<module:model/ViolenciaRequest>} 
     */
    constructor(tipoAtendimento, primeiroAtendimento, corRaca, sexoGenero, violencias) { 
        
        AnamneseInicialRequest.initialize(this, tipoAtendimento, primeiroAtendimento, corRaca, sexoGenero, violencias);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tipoAtendimento, primeiroAtendimento, corRaca, sexoGenero, violencias) { 
        obj['tipoAtendimento'] = tipoAtendimento;
        obj['primeiroAtendimento'] = primeiroAtendimento;
        obj['corRaca'] = corRaca;
        obj['sexoGenero'] = sexoGenero;
        obj['violencias'] = violencias;
    }

    /**
     * Constructs a <code>AnamneseInicialRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AnamneseInicialRequest} obj Optional instance to populate.
     * @return {module:model/AnamneseInicialRequest} The populated <code>AnamneseInicialRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnamneseInicialRequest();

            if (data.hasOwnProperty('tipoAtendimento')) {
                obj['tipoAtendimento'] = ApiClient.convertToType(data['tipoAtendimento'], 'String');
            }
            if (data.hasOwnProperty('primeiroAtendimento')) {
                obj['primeiroAtendimento'] = ApiClient.convertToType(data['primeiroAtendimento'], 'Boolean');
            }
            if (data.hasOwnProperty('territorio')) {
                obj['territorio'] = ApiClient.convertToType(data['territorio'], 'String');
            }
            if (data.hasOwnProperty('corRaca')) {
                obj['corRaca'] = ApiClient.convertToType(data['corRaca'], 'String');
            }
            if (data.hasOwnProperty('sexoGenero')) {
                obj['sexoGenero'] = ApiClient.convertToType(data['sexoGenero'], 'String');
            }
            if (data.hasOwnProperty('sexoGeneroOutro')) {
                obj['sexoGeneroOutro'] = ApiClient.convertToType(data['sexoGeneroOutro'], 'String');
            }
            if (data.hasOwnProperty('violencias')) {
                obj['violencias'] = ApiClient.convertToType(data['violencias'], [ViolenciaRequest]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnamneseInicialRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnamneseInicialRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AnamneseInicialRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['tipoAtendimento'] && !(typeof data['tipoAtendimento'] === 'string' || data['tipoAtendimento'] instanceof String)) {
            throw new Error("Expected the field `tipoAtendimento` to be a primitive type in the JSON string but got " + data['tipoAtendimento']);
        }
        // ensure the json data is a string
        if (data['territorio'] && !(typeof data['territorio'] === 'string' || data['territorio'] instanceof String)) {
            throw new Error("Expected the field `territorio` to be a primitive type in the JSON string but got " + data['territorio']);
        }
        // ensure the json data is a string
        if (data['corRaca'] && !(typeof data['corRaca'] === 'string' || data['corRaca'] instanceof String)) {
            throw new Error("Expected the field `corRaca` to be a primitive type in the JSON string but got " + data['corRaca']);
        }
        // ensure the json data is a string
        if (data['sexoGenero'] && !(typeof data['sexoGenero'] === 'string' || data['sexoGenero'] instanceof String)) {
            throw new Error("Expected the field `sexoGenero` to be a primitive type in the JSON string but got " + data['sexoGenero']);
        }
        // ensure the json data is a string
        if (data['sexoGeneroOutro'] && !(typeof data['sexoGeneroOutro'] === 'string' || data['sexoGeneroOutro'] instanceof String)) {
            throw new Error("Expected the field `sexoGeneroOutro` to be a primitive type in the JSON string but got " + data['sexoGeneroOutro']);
        }
        if (data['violencias']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['violencias'])) {
                throw new Error("Expected the field `violencias` to be an array in the JSON data but got " + data['violencias']);
            }
            // validate the optional field `violencias` (array)
            for (const item of data['violencias']) {
                ViolenciaRequest.validateJSON(item);
            };
        }

        return true;
    }


}

AnamneseInicialRequest.RequiredProperties = ["tipoAtendimento", "primeiroAtendimento", "corRaca", "sexoGenero", "violencias"];

/**
 * @member {String} tipoAtendimento
 */
AnamneseInicialRequest.prototype['tipoAtendimento'] = undefined;

/**
 * @member {Boolean} primeiroAtendimento
 */
AnamneseInicialRequest.prototype['primeiroAtendimento'] = undefined;

/**
 * @member {String} territorio
 */
AnamneseInicialRequest.prototype['territorio'] = undefined;

/**
 * @member {String} corRaca
 */
AnamneseInicialRequest.prototype['corRaca'] = undefined;

/**
 * @member {String} sexoGenero
 */
AnamneseInicialRequest.prototype['sexoGenero'] = undefined;

/**
 * @member {String} sexoGeneroOutro
 */
AnamneseInicialRequest.prototype['sexoGeneroOutro'] = undefined;

/**
 * @member {Array.<module:model/ViolenciaRequest>} violencias
 */
AnamneseInicialRequest.prototype['violencias'] = undefined;






export default AnamneseInicialRequest;

