/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AnamneseInicialResponse from './AnamneseInicialResponse';
import AnamneseTecnicaResponse from './AnamneseTecnicaResponse';
import ObsJuridicaResponse from './ObsJuridicaResponse';
import ProntuarioResponse from './ProntuarioResponse';
import TimelineEventoResponse from './TimelineEventoResponse';

/**
 * The AtendimentoDetalheResponse model module.
 * @module model/AtendimentoDetalheResponse
 * @version 1.0.0
 */
class AtendimentoDetalheResponse {
    /**
     * Constructs a new <code>AtendimentoDetalheResponse</code>.
     * @alias module:model/AtendimentoDetalheResponse
     */
    constructor() { 
        
        AtendimentoDetalheResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AtendimentoDetalheResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AtendimentoDetalheResponse} obj Optional instance to populate.
     * @return {module:model/AtendimentoDetalheResponse} The populated <code>AtendimentoDetalheResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AtendimentoDetalheResponse();

            if (data.hasOwnProperty('agendamentoId')) {
                obj['agendamentoId'] = ApiClient.convertToType(data['agendamentoId'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'Date');
            }
            if (data.hasOwnProperty('horario')) {
                obj['horario'] = ApiClient.convertToType(data['horario'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('anamneseInicial')) {
                obj['anamneseInicial'] = AnamneseInicialResponse.constructFromObject(data['anamneseInicial']);
            }
            if (data.hasOwnProperty('anamneseTecnica')) {
                obj['anamneseTecnica'] = AnamneseTecnicaResponse.constructFromObject(data['anamneseTecnica']);
            }
            if (data.hasOwnProperty('prontuario')) {
                obj['prontuario'] = ProntuarioResponse.constructFromObject(data['prontuario']);
            }
            if (data.hasOwnProperty('obsJuridica')) {
                obj['obsJuridica'] = ObsJuridicaResponse.constructFromObject(data['obsJuridica']);
            }
            if (data.hasOwnProperty('timeline')) {
                obj['timeline'] = ApiClient.convertToType(data['timeline'], [TimelineEventoResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AtendimentoDetalheResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AtendimentoDetalheResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['agendamentoId'] && !(typeof data['agendamentoId'] === 'string' || data['agendamentoId'] instanceof String)) {
            throw new Error("Expected the field `agendamentoId` to be a primitive type in the JSON string but got " + data['agendamentoId']);
        }
        // ensure the json data is a string
        if (data['horario'] && !(typeof data['horario'] === 'string' || data['horario'] instanceof String)) {
            throw new Error("Expected the field `horario` to be a primitive type in the JSON string but got " + data['horario']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // validate the optional field `anamneseInicial`
        if (data['anamneseInicial']) { // data not null
          AnamneseInicialResponse.validateJSON(data['anamneseInicial']);
        }
        // validate the optional field `anamneseTecnica`
        if (data['anamneseTecnica']) { // data not null
          AnamneseTecnicaResponse.validateJSON(data['anamneseTecnica']);
        }
        // validate the optional field `prontuario`
        if (data['prontuario']) { // data not null
          ProntuarioResponse.validateJSON(data['prontuario']);
        }
        // validate the optional field `obsJuridica`
        if (data['obsJuridica']) { // data not null
          ObsJuridicaResponse.validateJSON(data['obsJuridica']);
        }
        if (data['timeline']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['timeline'])) {
                throw new Error("Expected the field `timeline` to be an array in the JSON data but got " + data['timeline']);
            }
            // validate the optional field `timeline` (array)
            for (const item of data['timeline']) {
                TimelineEventoResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} agendamentoId
 */
AtendimentoDetalheResponse.prototype['agendamentoId'] = undefined;

/**
 * @member {Date} data
 */
AtendimentoDetalheResponse.prototype['data'] = undefined;

/**
 * @member {String} horario
 */
AtendimentoDetalheResponse.prototype['horario'] = undefined;

/**
 * @member {String} status
 */
AtendimentoDetalheResponse.prototype['status'] = undefined;

/**
 * @member {module:model/AnamneseInicialResponse} anamneseInicial
 */
AtendimentoDetalheResponse.prototype['anamneseInicial'] = undefined;

/**
 * @member {module:model/AnamneseTecnicaResponse} anamneseTecnica
 */
AtendimentoDetalheResponse.prototype['anamneseTecnica'] = undefined;

/**
 * @member {module:model/ProntuarioResponse} prontuario
 */
AtendimentoDetalheResponse.prototype['prontuario'] = undefined;

/**
 * @member {module:model/ObsJuridicaResponse} obsJuridica
 */
AtendimentoDetalheResponse.prototype['obsJuridica'] = undefined;

/**
 * @member {Array.<module:model/TimelineEventoResponse>} timeline
 */
AtendimentoDetalheResponse.prototype['timeline'] = undefined;






export default AtendimentoDetalheResponse;

