/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AtendimentoRelatorioResponse model module.
 * @module model/AtendimentoRelatorioResponse
 * @version 1.0.0
 */
class AtendimentoRelatorioResponse {
    /**
     * Constructs a new <code>AtendimentoRelatorioResponse</code>.
     * @alias module:model/AtendimentoRelatorioResponse
     */
    constructor() { 
        
        AtendimentoRelatorioResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AtendimentoRelatorioResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AtendimentoRelatorioResponse} obj Optional instance to populate.
     * @return {module:model/AtendimentoRelatorioResponse} The populated <code>AtendimentoRelatorioResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AtendimentoRelatorioResponse();

            if (data.hasOwnProperty('agendamentoId')) {
                obj['agendamentoId'] = ApiClient.convertToType(data['agendamentoId'], 'String');
            }
            if (data.hasOwnProperty('pacienteNome')) {
                obj['pacienteNome'] = ApiClient.convertToType(data['pacienteNome'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'Date');
            }
            if (data.hasOwnProperty('horario')) {
                obj['horario'] = ApiClient.convertToType(data['horario'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('atendente')) {
                obj['atendente'] = ApiClient.convertToType(data['atendente'], 'String');
            }
            if (data.hasOwnProperty('criadoEm')) {
                obj['criadoEm'] = ApiClient.convertToType(data['criadoEm'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AtendimentoRelatorioResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AtendimentoRelatorioResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['agendamentoId'] && !(typeof data['agendamentoId'] === 'string' || data['agendamentoId'] instanceof String)) {
            throw new Error("Expected the field `agendamentoId` to be a primitive type in the JSON string but got " + data['agendamentoId']);
        }
        // ensure the json data is a string
        if (data['pacienteNome'] && !(typeof data['pacienteNome'] === 'string' || data['pacienteNome'] instanceof String)) {
            throw new Error("Expected the field `pacienteNome` to be a primitive type in the JSON string but got " + data['pacienteNome']);
        }
        // ensure the json data is a string
        if (data['horario'] && !(typeof data['horario'] === 'string' || data['horario'] instanceof String)) {
            throw new Error("Expected the field `horario` to be a primitive type in the JSON string but got " + data['horario']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['atendente'] && !(typeof data['atendente'] === 'string' || data['atendente'] instanceof String)) {
            throw new Error("Expected the field `atendente` to be a primitive type in the JSON string but got " + data['atendente']);
        }

        return true;
    }


}



/**
 * @member {String} agendamentoId
 */
AtendimentoRelatorioResponse.prototype['agendamentoId'] = undefined;

/**
 * @member {String} pacienteNome
 */
AtendimentoRelatorioResponse.prototype['pacienteNome'] = undefined;

/**
 * @member {Date} data
 */
AtendimentoRelatorioResponse.prototype['data'] = undefined;

/**
 * @member {String} horario
 */
AtendimentoRelatorioResponse.prototype['horario'] = undefined;

/**
 * @member {String} status
 */
AtendimentoRelatorioResponse.prototype['status'] = undefined;

/**
 * @member {String} atendente
 */
AtendimentoRelatorioResponse.prototype['atendente'] = undefined;

/**
 * @member {Date} criadoEm
 */
AtendimentoRelatorioResponse.prototype['criadoEm'] = undefined;






export default AtendimentoRelatorioResponse;

