/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContadoresResponse model module.
 * @module model/ContadoresResponse
 * @version 1.0.0
 */
class ContadoresResponse {
    /**
     * Constructs a new <code>ContadoresResponse</code>.
     * @alias module:model/ContadoresResponse
     */
    constructor() { 
        
        ContadoresResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContadoresResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContadoresResponse} obj Optional instance to populate.
     * @return {module:model/ContadoresResponse} The populated <code>ContadoresResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContadoresResponse();

            if (data.hasOwnProperty('aguardando')) {
                obj['aguardando'] = ApiClient.convertToType(data['aguardando'], 'Number');
            }
            if (data.hasOwnProperty('emAtendimento')) {
                obj['emAtendimento'] = ApiClient.convertToType(data['emAtendimento'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContadoresResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContadoresResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} aguardando
 */
ContadoresResponse.prototype['aguardando'] = undefined;

/**
 * @member {Number} emAtendimento
 */
ContadoresResponse.prototype['emAtendimento'] = undefined;






export default ContadoresResponse;

