/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateUsuarioRequest model module.
 * @module model/CreateUsuarioRequest
 * @version 1.0.0
 */
class CreateUsuarioRequest {
    /**
     * Constructs a new <code>CreateUsuarioRequest</code>.
     * @alias module:model/CreateUsuarioRequest
     * @param nome {String} 
     * @param email {String} 
     * @param senha {String} 
     * @param perfil {module:model/CreateUsuarioRequest.PerfilEnum} 
     */
    constructor(nome, email, senha, perfil) { 
        
        CreateUsuarioRequest.initialize(this, nome, email, senha, perfil);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nome, email, senha, perfil) { 
        obj['nome'] = nome;
        obj['email'] = email;
        obj['senha'] = senha;
        obj['perfil'] = perfil;
    }

    /**
     * Constructs a <code>CreateUsuarioRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUsuarioRequest} obj Optional instance to populate.
     * @return {module:model/CreateUsuarioRequest} The populated <code>CreateUsuarioRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUsuarioRequest();

            if (data.hasOwnProperty('nome')) {
                obj['nome'] = ApiClient.convertToType(data['nome'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('senha')) {
                obj['senha'] = ApiClient.convertToType(data['senha'], 'String');
            }
            if (data.hasOwnProperty('perfil')) {
                obj['perfil'] = ApiClient.convertToType(data['perfil'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateUsuarioRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateUsuarioRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateUsuarioRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['nome'] && !(typeof data['nome'] === 'string' || data['nome'] instanceof String)) {
            throw new Error("Expected the field `nome` to be a primitive type in the JSON string but got " + data['nome']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['senha'] && !(typeof data['senha'] === 'string' || data['senha'] instanceof String)) {
            throw new Error("Expected the field `senha` to be a primitive type in the JSON string but got " + data['senha']);
        }
        // ensure the json data is a string
        if (data['perfil'] && !(typeof data['perfil'] === 'string' || data['perfil'] instanceof String)) {
            throw new Error("Expected the field `perfil` to be a primitive type in the JSON string but got " + data['perfil']);
        }

        return true;
    }


}

CreateUsuarioRequest.RequiredProperties = ["nome", "email", "senha", "perfil"];

/**
 * @member {String} nome
 */
CreateUsuarioRequest.prototype['nome'] = undefined;

/**
 * @member {String} email
 */
CreateUsuarioRequest.prototype['email'] = undefined;

/**
 * @member {String} senha
 */
CreateUsuarioRequest.prototype['senha'] = undefined;

/**
 * @member {module:model/CreateUsuarioRequest.PerfilEnum} perfil
 */
CreateUsuarioRequest.prototype['perfil'] = undefined;





/**
 * Allowed values for the <code>perfil</code> property.
 * @enum {String}
 * @readonly
 */
CreateUsuarioRequest['PerfilEnum'] = {

    /**
     * value: "ATENDENTE"
     * @const
     */
    "ATENDENTE": "ATENDENTE",

    /**
     * value: "TECNICA"
     * @const
     */
    "TECNICA": "TECNICA",

    /**
     * value: "CIS"
     * @const
     */
    "CIS": "CIS",

    /**
     * value: "NPJ"
     * @const
     */
    "NPJ": "NPJ",

    /**
     * value: "ADMIN"
     * @const
     */
    "ADMIN": "ADMIN"
};



export default CreateUsuarioRequest;

