/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EncaminhamentoResponse model module.
 * @module model/EncaminhamentoResponse
 * @version 1.0.0
 */
class EncaminhamentoResponse {
    /**
     * Constructs a new <code>EncaminhamentoResponse</code>.
     * @alias module:model/EncaminhamentoResponse
     */
    constructor() { 
        
        EncaminhamentoResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EncaminhamentoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EncaminhamentoResponse} obj Optional instance to populate.
     * @return {module:model/EncaminhamentoResponse} The populated <code>EncaminhamentoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EncaminhamentoResponse();

            if (data.hasOwnProperty('agendamentoId')) {
                obj['agendamentoId'] = ApiClient.convertToType(data['agendamentoId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('origemPerfil')) {
                obj['origemPerfil'] = ApiClient.convertToType(data['origemPerfil'], 'String');
            }
            if (data.hasOwnProperty('destinoPerfil')) {
                obj['destinoPerfil'] = ApiClient.convertToType(data['destinoPerfil'], 'String');
            }
            if (data.hasOwnProperty('criadoEm')) {
                obj['criadoEm'] = ApiClient.convertToType(data['criadoEm'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EncaminhamentoResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EncaminhamentoResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['agendamentoId'] && !(typeof data['agendamentoId'] === 'string' || data['agendamentoId'] instanceof String)) {
            throw new Error("Expected the field `agendamentoId` to be a primitive type in the JSON string but got " + data['agendamentoId']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['origemPerfil'] && !(typeof data['origemPerfil'] === 'string' || data['origemPerfil'] instanceof String)) {
            throw new Error("Expected the field `origemPerfil` to be a primitive type in the JSON string but got " + data['origemPerfil']);
        }
        // ensure the json data is a string
        if (data['destinoPerfil'] && !(typeof data['destinoPerfil'] === 'string' || data['destinoPerfil'] instanceof String)) {
            throw new Error("Expected the field `destinoPerfil` to be a primitive type in the JSON string but got " + data['destinoPerfil']);
        }

        return true;
    }


}



/**
 * @member {String} agendamentoId
 */
EncaminhamentoResponse.prototype['agendamentoId'] = undefined;

/**
 * @member {String} status
 */
EncaminhamentoResponse.prototype['status'] = undefined;

/**
 * @member {String} origemPerfil
 */
EncaminhamentoResponse.prototype['origemPerfil'] = undefined;

/**
 * @member {String} destinoPerfil
 */
EncaminhamentoResponse.prototype['destinoPerfil'] = undefined;

/**
 * @member {Date} criadoEm
 */
EncaminhamentoResponse.prototype['criadoEm'] = undefined;






export default EncaminhamentoResponse;

