/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EncaminhamentoTecnicoResponse model module.
 * @module model/EncaminhamentoTecnicoResponse
 * @version 1.0.0
 */
class EncaminhamentoTecnicoResponse {
    /**
     * Constructs a new <code>EncaminhamentoTecnicoResponse</code>.
     * @alias module:model/EncaminhamentoTecnicoResponse
     */
    constructor() { 
        
        EncaminhamentoTecnicoResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EncaminhamentoTecnicoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EncaminhamentoTecnicoResponse} obj Optional instance to populate.
     * @return {module:model/EncaminhamentoTecnicoResponse} The populated <code>EncaminhamentoTecnicoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EncaminhamentoTecnicoResponse();

            if (data.hasOwnProperty('encaminhamento')) {
                obj['encaminhamento'] = ApiClient.convertToType(data['encaminhamento'], 'String');
            }
            if (data.hasOwnProperty('encaminhamentoOutro')) {
                obj['encaminhamentoOutro'] = ApiClient.convertToType(data['encaminhamentoOutro'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EncaminhamentoTecnicoResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EncaminhamentoTecnicoResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['encaminhamento'] && !(typeof data['encaminhamento'] === 'string' || data['encaminhamento'] instanceof String)) {
            throw new Error("Expected the field `encaminhamento` to be a primitive type in the JSON string but got " + data['encaminhamento']);
        }
        // ensure the json data is a string
        if (data['encaminhamentoOutro'] && !(typeof data['encaminhamentoOutro'] === 'string' || data['encaminhamentoOutro'] instanceof String)) {
            throw new Error("Expected the field `encaminhamentoOutro` to be a primitive type in the JSON string but got " + data['encaminhamentoOutro']);
        }

        return true;
    }


}



/**
 * @member {String} encaminhamento
 */
EncaminhamentoTecnicoResponse.prototype['encaminhamento'] = undefined;

/**
 * @member {String} encaminhamentoOutro
 */
EncaminhamentoTecnicoResponse.prototype['encaminhamentoOutro'] = undefined;






export default EncaminhamentoTecnicoResponse;

