/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EncaminhamentoTecnicoRequest model module.
 * @module model/EncaminhamentoTecnicoRequest
 * @version 1.0.0
 */
class EncaminhamentoTecnicoRequest {
    /**
     * Constructs a new <code>EncaminhamentoTecnicoRequest</code>.
     * @alias module:model/EncaminhamentoTecnicoRequest
     * @param encaminhamento {String} 
     */
    constructor(encaminhamento) { 
        
        EncaminhamentoTecnicoRequest.initialize(this, encaminhamento);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, encaminhamento) { 
        obj['encaminhamento'] = encaminhamento;
    }

    /**
     * Constructs a <code>EncaminhamentoTecnicoRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EncaminhamentoTecnicoRequest} obj Optional instance to populate.
     * @return {module:model/EncaminhamentoTecnicoRequest} The populated <code>EncaminhamentoTecnicoRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EncaminhamentoTecnicoRequest();

            if (data.hasOwnProperty('encaminhamento')) {
                obj['encaminhamento'] = ApiClient.convertToType(data['encaminhamento'], 'String');
            }
            if (data.hasOwnProperty('encaminhamentoOutro')) {
                obj['encaminhamentoOutro'] = ApiClient.convertToType(data['encaminhamentoOutro'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EncaminhamentoTecnicoRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EncaminhamentoTecnicoRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EncaminhamentoTecnicoRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['encaminhamento'] && !(typeof data['encaminhamento'] === 'string' || data['encaminhamento'] instanceof String)) {
            throw new Error("Expected the field `encaminhamento` to be a primitive type in the JSON string but got " + data['encaminhamento']);
        }
        // ensure the json data is a string
        if (data['encaminhamentoOutro'] && !(typeof data['encaminhamentoOutro'] === 'string' || data['encaminhamentoOutro'] instanceof String)) {
            throw new Error("Expected the field `encaminhamentoOutro` to be a primitive type in the JSON string but got " + data['encaminhamentoOutro']);
        }

        return true;
    }


}

EncaminhamentoTecnicoRequest.RequiredProperties = ["encaminhamento"];

/**
 * @member {String} encaminhamento
 */
EncaminhamentoTecnicoRequest.prototype['encaminhamento'] = undefined;

/**
 * @member {String} encaminhamentoOutro
 */
EncaminhamentoTecnicoRequest.prototype['encaminhamentoOutro'] = undefined;






export default EncaminhamentoTecnicoRequest;

