/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HorariosDisponiveisResponse model module.
 * @module model/HorariosDisponiveisResponse
 * @version 1.0.0
 */
class HorariosDisponiveisResponse {
    /**
     * Constructs a new <code>HorariosDisponiveisResponse</code>.
     * @alias module:model/HorariosDisponiveisResponse
     */
    constructor() { 
        
        HorariosDisponiveisResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HorariosDisponiveisResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HorariosDisponiveisResponse} obj Optional instance to populate.
     * @return {module:model/HorariosDisponiveisResponse} The populated <code>HorariosDisponiveisResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HorariosDisponiveisResponse();

            if (data.hasOwnProperty('horarios')) {
                obj['horarios'] = ApiClient.convertToType(data['horarios'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HorariosDisponiveisResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HorariosDisponiveisResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['horarios'])) {
            throw new Error("Expected the field `horarios` to be an array in the JSON data but got " + data['horarios']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} horarios
 */
HorariosDisponiveisResponse.prototype['horarios'] = undefined;






export default HorariosDisponiveisResponse;

