/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VolumeDiarioResponse from './VolumeDiarioResponse';

/**
 * The KpiResponse model module.
 * @module model/KpiResponse
 * @version 1.0.0
 */
class KpiResponse {
    /**
     * Constructs a new <code>KpiResponse</code>.
     * @alias module:model/KpiResponse
     */
    constructor() { 
        
        KpiResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>KpiResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KpiResponse} obj Optional instance to populate.
     * @return {module:model/KpiResponse} The populated <code>KpiResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KpiResponse();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('porStatus')) {
                obj['porStatus'] = ApiClient.convertToType(data['porStatus'], {'String': 'Number'});
            }
            if (data.hasOwnProperty('porDia')) {
                obj['porDia'] = ApiClient.convertToType(data['porDia'], [VolumeDiarioResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>KpiResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>KpiResponse</code>.
     */
    static validateJSON(data) {
        if (data['porDia']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['porDia'])) {
                throw new Error("Expected the field `porDia` to be an array in the JSON data but got " + data['porDia']);
            }
            // validate the optional field `porDia` (array)
            for (const item of data['porDia']) {
                VolumeDiarioResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} total
 */
KpiResponse.prototype['total'] = undefined;

/**
 * @member {Object.<String, Number>} porStatus
 */
KpiResponse.prototype['porStatus'] = undefined;

/**
 * @member {Array.<module:model/VolumeDiarioResponse>} porDia
 */
KpiResponse.prototype['porDia'] = undefined;






export default KpiResponse;

