/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LgpdResponse model module.
 * @module model/LgpdResponse
 * @version 1.0.0
 */
class LgpdResponse {
    /**
     * Constructs a new <code>LgpdResponse</code>.
     * @alias module:model/LgpdResponse
     */
    constructor() { 
        
        LgpdResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LgpdResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LgpdResponse} obj Optional instance to populate.
     * @return {module:model/LgpdResponse} The populated <code>LgpdResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LgpdResponse();

            if (data.hasOwnProperty('lgpdAceito')) {
                obj['lgpdAceito'] = ApiClient.convertToType(data['lgpdAceito'], 'Boolean');
            }
            if (data.hasOwnProperty('lgpdData')) {
                obj['lgpdData'] = ApiClient.convertToType(data['lgpdData'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LgpdResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LgpdResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} lgpdAceito
 */
LgpdResponse.prototype['lgpdAceito'] = undefined;

/**
 * @member {Date} lgpdData
 */
LgpdResponse.prototype['lgpdData'] = undefined;






export default LgpdResponse;

