/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MeResponse model module.
 * @module model/MeResponse
 * @version 1.0.0
 */
class MeResponse {
    /**
     * Constructs a new <code>MeResponse</code>.
     * @alias module:model/MeResponse
     */
    constructor() { 
        
        MeResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MeResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeResponse} obj Optional instance to populate.
     * @return {module:model/MeResponse} The populated <code>MeResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MeResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('nome')) {
                obj['nome'] = ApiClient.convertToType(data['nome'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('perfil')) {
                obj['perfil'] = ApiClient.convertToType(data['perfil'], 'String');
            }
            if (data.hasOwnProperty('lgpdAceito')) {
                obj['lgpdAceito'] = ApiClient.convertToType(data['lgpdAceito'], 'Boolean');
            }
            if (data.hasOwnProperty('lgpdData')) {
                obj['lgpdData'] = ApiClient.convertToType(data['lgpdData'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MeResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MeResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['nome'] && !(typeof data['nome'] === 'string' || data['nome'] instanceof String)) {
            throw new Error("Expected the field `nome` to be a primitive type in the JSON string but got " + data['nome']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['perfil'] && !(typeof data['perfil'] === 'string' || data['perfil'] instanceof String)) {
            throw new Error("Expected the field `perfil` to be a primitive type in the JSON string but got " + data['perfil']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
MeResponse.prototype['id'] = undefined;

/**
 * @member {String} nome
 */
MeResponse.prototype['nome'] = undefined;

/**
 * @member {String} email
 */
MeResponse.prototype['email'] = undefined;

/**
 * @member {String} perfil
 */
MeResponse.prototype['perfil'] = undefined;

/**
 * @member {Boolean} lgpdAceito
 */
MeResponse.prototype['lgpdAceito'] = undefined;

/**
 * @member {Date} lgpdData
 */
MeResponse.prototype['lgpdData'] = undefined;






export default MeResponse;

