/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ObjetivoResponse model module.
 * @module model/ObjetivoResponse
 * @version 1.0.0
 */
class ObjetivoResponse {
    /**
     * Constructs a new <code>ObjetivoResponse</code>.
     * @alias module:model/ObjetivoResponse
     */
    constructor() { 
        
        ObjetivoResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ObjetivoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ObjetivoResponse} obj Optional instance to populate.
     * @return {module:model/ObjetivoResponse} The populated <code>ObjetivoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjetivoResponse();

            if (data.hasOwnProperty('objetivo')) {
                obj['objetivo'] = ApiClient.convertToType(data['objetivo'], 'String');
            }
            if (data.hasOwnProperty('objetivoOutro')) {
                obj['objetivoOutro'] = ApiClient.convertToType(data['objetivoOutro'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ObjetivoResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ObjetivoResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['objetivo'] && !(typeof data['objetivo'] === 'string' || data['objetivo'] instanceof String)) {
            throw new Error("Expected the field `objetivo` to be a primitive type in the JSON string but got " + data['objetivo']);
        }
        // ensure the json data is a string
        if (data['objetivoOutro'] && !(typeof data['objetivoOutro'] === 'string' || data['objetivoOutro'] instanceof String)) {
            throw new Error("Expected the field `objetivoOutro` to be a primitive type in the JSON string but got " + data['objetivoOutro']);
        }

        return true;
    }


}



/**
 * @member {String} objetivo
 */
ObjetivoResponse.prototype['objetivo'] = undefined;

/**
 * @member {String} objetivoOutro
 */
ObjetivoResponse.prototype['objetivoOutro'] = undefined;






export default ObjetivoResponse;

