/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ObjetivoRequest model module.
 * @module model/ObjetivoRequest
 * @version 1.0.0
 */
class ObjetivoRequest {
    /**
     * Constructs a new <code>ObjetivoRequest</code>.
     * @alias module:model/ObjetivoRequest
     * @param objetivo {String} 
     */
    constructor(objetivo) { 
        
        ObjetivoRequest.initialize(this, objetivo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, objetivo) { 
        obj['objetivo'] = objetivo;
    }

    /**
     * Constructs a <code>ObjetivoRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ObjetivoRequest} obj Optional instance to populate.
     * @return {module:model/ObjetivoRequest} The populated <code>ObjetivoRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjetivoRequest();

            if (data.hasOwnProperty('objetivo')) {
                obj['objetivo'] = ApiClient.convertToType(data['objetivo'], 'String');
            }
            if (data.hasOwnProperty('objetivoOutro')) {
                obj['objetivoOutro'] = ApiClient.convertToType(data['objetivoOutro'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ObjetivoRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ObjetivoRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ObjetivoRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['objetivo'] && !(typeof data['objetivo'] === 'string' || data['objetivo'] instanceof String)) {
            throw new Error("Expected the field `objetivo` to be a primitive type in the JSON string but got " + data['objetivo']);
        }
        // ensure the json data is a string
        if (data['objetivoOutro'] && !(typeof data['objetivoOutro'] === 'string' || data['objetivoOutro'] instanceof String)) {
            throw new Error("Expected the field `objetivoOutro` to be a primitive type in the JSON string but got " + data['objetivoOutro']);
        }

        return true;
    }


}

ObjetivoRequest.RequiredProperties = ["objetivo"];

/**
 * @member {String} objetivo
 */
ObjetivoRequest.prototype['objetivo'] = undefined;

/**
 * @member {String} objetivoOutro
 */
ObjetivoRequest.prototype['objetivoOutro'] = undefined;






export default ObjetivoRequest;

