/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ObsJuridicaRequest model module.
 * @module model/ObsJuridicaRequest
 * @version 1.0.0
 */
class ObsJuridicaRequest {
    /**
     * Constructs a new <code>ObsJuridicaRequest</code>.
     * @alias module:model/ObsJuridicaRequest
     * @param encaminhamentosLegais {String} 
     */
    constructor(encaminhamentosLegais) { 
        
        ObsJuridicaRequest.initialize(this, encaminhamentosLegais);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, encaminhamentosLegais) { 
        obj['encaminhamentosLegais'] = encaminhamentosLegais;
    }

    /**
     * Constructs a <code>ObsJuridicaRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ObsJuridicaRequest} obj Optional instance to populate.
     * @return {module:model/ObsJuridicaRequest} The populated <code>ObsJuridicaRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObsJuridicaRequest();

            if (data.hasOwnProperty('encaminhamentosLegais')) {
                obj['encaminhamentosLegais'] = ApiClient.convertToType(data['encaminhamentosLegais'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ObsJuridicaRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ObsJuridicaRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ObsJuridicaRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['encaminhamentosLegais'] && !(typeof data['encaminhamentosLegais'] === 'string' || data['encaminhamentosLegais'] instanceof String)) {
            throw new Error("Expected the field `encaminhamentosLegais` to be a primitive type in the JSON string but got " + data['encaminhamentosLegais']);
        }

        return true;
    }


}

ObsJuridicaRequest.RequiredProperties = ["encaminhamentosLegais"];

/**
 * @member {String} encaminhamentosLegais
 */
ObsJuridicaRequest.prototype['encaminhamentosLegais'] = undefined;






export default ObsJuridicaRequest;

