/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ObsJuridicaResponse model module.
 * @module model/ObsJuridicaResponse
 * @version 1.0.0
 */
class ObsJuridicaResponse {
    /**
     * Constructs a new <code>ObsJuridicaResponse</code>.
     * @alias module:model/ObsJuridicaResponse
     */
    constructor() { 
        
        ObsJuridicaResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ObsJuridicaResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ObsJuridicaResponse} obj Optional instance to populate.
     * @return {module:model/ObsJuridicaResponse} The populated <code>ObsJuridicaResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObsJuridicaResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('agendamentoId')) {
                obj['agendamentoId'] = ApiClient.convertToType(data['agendamentoId'], 'String');
            }
            if (data.hasOwnProperty('pacienteNome')) {
                obj['pacienteNome'] = ApiClient.convertToType(data['pacienteNome'], 'String');
            }
            if (data.hasOwnProperty('encaminhamentosLegais')) {
                obj['encaminhamentosLegais'] = ApiClient.convertToType(data['encaminhamentosLegais'], 'String');
            }
            if (data.hasOwnProperty('criadoPor')) {
                obj['criadoPor'] = ApiClient.convertToType(data['criadoPor'], 'String');
            }
            if (data.hasOwnProperty('criadoEm')) {
                obj['criadoEm'] = ApiClient.convertToType(data['criadoEm'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ObsJuridicaResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ObsJuridicaResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['agendamentoId'] && !(typeof data['agendamentoId'] === 'string' || data['agendamentoId'] instanceof String)) {
            throw new Error("Expected the field `agendamentoId` to be a primitive type in the JSON string but got " + data['agendamentoId']);
        }
        // ensure the json data is a string
        if (data['pacienteNome'] && !(typeof data['pacienteNome'] === 'string' || data['pacienteNome'] instanceof String)) {
            throw new Error("Expected the field `pacienteNome` to be a primitive type in the JSON string but got " + data['pacienteNome']);
        }
        // ensure the json data is a string
        if (data['encaminhamentosLegais'] && !(typeof data['encaminhamentosLegais'] === 'string' || data['encaminhamentosLegais'] instanceof String)) {
            throw new Error("Expected the field `encaminhamentosLegais` to be a primitive type in the JSON string but got " + data['encaminhamentosLegais']);
        }
        // ensure the json data is a string
        if (data['criadoPor'] && !(typeof data['criadoPor'] === 'string' || data['criadoPor'] instanceof String)) {
            throw new Error("Expected the field `criadoPor` to be a primitive type in the JSON string but got " + data['criadoPor']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ObsJuridicaResponse.prototype['id'] = undefined;

/**
 * @member {String} agendamentoId
 */
ObsJuridicaResponse.prototype['agendamentoId'] = undefined;

/**
 * @member {String} pacienteNome
 */
ObsJuridicaResponse.prototype['pacienteNome'] = undefined;

/**
 * @member {String} encaminhamentosLegais
 */
ObsJuridicaResponse.prototype['encaminhamentosLegais'] = undefined;

/**
 * @member {String} criadoPor
 */
ObsJuridicaResponse.prototype['criadoPor'] = undefined;

/**
 * @member {Date} criadoEm
 */
ObsJuridicaResponse.prototype['criadoEm'] = undefined;






export default ObsJuridicaResponse;

