/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrientacaoResponse model module.
 * @module model/OrientacaoResponse
 * @version 1.0.0
 */
class OrientacaoResponse {
    /**
     * Constructs a new <code>OrientacaoResponse</code>.
     * @alias module:model/OrientacaoResponse
     */
    constructor() { 
        
        OrientacaoResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrientacaoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrientacaoResponse} obj Optional instance to populate.
     * @return {module:model/OrientacaoResponse} The populated <code>OrientacaoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrientacaoResponse();

            if (data.hasOwnProperty('orientacao')) {
                obj['orientacao'] = ApiClient.convertToType(data['orientacao'], 'String');
            }
            if (data.hasOwnProperty('orientacaoOutro')) {
                obj['orientacaoOutro'] = ApiClient.convertToType(data['orientacaoOutro'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrientacaoResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrientacaoResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['orientacao'] && !(typeof data['orientacao'] === 'string' || data['orientacao'] instanceof String)) {
            throw new Error("Expected the field `orientacao` to be a primitive type in the JSON string but got " + data['orientacao']);
        }
        // ensure the json data is a string
        if (data['orientacaoOutro'] && !(typeof data['orientacaoOutro'] === 'string' || data['orientacaoOutro'] instanceof String)) {
            throw new Error("Expected the field `orientacaoOutro` to be a primitive type in the JSON string but got " + data['orientacaoOutro']);
        }

        return true;
    }


}



/**
 * @member {String} orientacao
 */
OrientacaoResponse.prototype['orientacao'] = undefined;

/**
 * @member {String} orientacaoOutro
 */
OrientacaoResponse.prototype['orientacaoOutro'] = undefined;






export default OrientacaoResponse;

