/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrientacaoRequest model module.
 * @module model/OrientacaoRequest
 * @version 1.0.0
 */
class OrientacaoRequest {
    /**
     * Constructs a new <code>OrientacaoRequest</code>.
     * @alias module:model/OrientacaoRequest
     * @param orientacao {String} 
     */
    constructor(orientacao) { 
        
        OrientacaoRequest.initialize(this, orientacao);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, orientacao) { 
        obj['orientacao'] = orientacao;
    }

    /**
     * Constructs a <code>OrientacaoRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrientacaoRequest} obj Optional instance to populate.
     * @return {module:model/OrientacaoRequest} The populated <code>OrientacaoRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrientacaoRequest();

            if (data.hasOwnProperty('orientacao')) {
                obj['orientacao'] = ApiClient.convertToType(data['orientacao'], 'String');
            }
            if (data.hasOwnProperty('orientacaoOutro')) {
                obj['orientacaoOutro'] = ApiClient.convertToType(data['orientacaoOutro'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrientacaoRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrientacaoRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OrientacaoRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['orientacao'] && !(typeof data['orientacao'] === 'string' || data['orientacao'] instanceof String)) {
            throw new Error("Expected the field `orientacao` to be a primitive type in the JSON string but got " + data['orientacao']);
        }
        // ensure the json data is a string
        if (data['orientacaoOutro'] && !(typeof data['orientacaoOutro'] === 'string' || data['orientacaoOutro'] instanceof String)) {
            throw new Error("Expected the field `orientacaoOutro` to be a primitive type in the JSON string but got " + data['orientacaoOutro']);
        }

        return true;
    }


}

OrientacaoRequest.RequiredProperties = ["orientacao"];

/**
 * @member {String} orientacao
 */
OrientacaoRequest.prototype['orientacao'] = undefined;

/**
 * @member {String} orientacaoOutro
 */
OrientacaoRequest.prototype['orientacaoOutro'] = undefined;






export default OrientacaoRequest;

