/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AtendimentoDetalheResponse from './AtendimentoDetalheResponse';

/**
 * The PacienteDetalheResponse model module.
 * @module model/PacienteDetalheResponse
 * @version 1.0.0
 */
class PacienteDetalheResponse {
    /**
     * Constructs a new <code>PacienteDetalheResponse</code>.
     * @alias module:model/PacienteDetalheResponse
     */
    constructor() { 
        
        PacienteDetalheResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PacienteDetalheResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PacienteDetalheResponse} obj Optional instance to populate.
     * @return {module:model/PacienteDetalheResponse} The populated <code>PacienteDetalheResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PacienteDetalheResponse();

            if (data.hasOwnProperty('pacienteId')) {
                obj['pacienteId'] = ApiClient.convertToType(data['pacienteId'], 'String');
            }
            if (data.hasOwnProperty('nome')) {
                obj['nome'] = ApiClient.convertToType(data['nome'], 'String');
            }
            if (data.hasOwnProperty('cpf')) {
                obj['cpf'] = ApiClient.convertToType(data['cpf'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('atendimentos')) {
                obj['atendimentos'] = ApiClient.convertToType(data['atendimentos'], [AtendimentoDetalheResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PacienteDetalheResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PacienteDetalheResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['pacienteId'] && !(typeof data['pacienteId'] === 'string' || data['pacienteId'] instanceof String)) {
            throw new Error("Expected the field `pacienteId` to be a primitive type in the JSON string but got " + data['pacienteId']);
        }
        // ensure the json data is a string
        if (data['nome'] && !(typeof data['nome'] === 'string' || data['nome'] instanceof String)) {
            throw new Error("Expected the field `nome` to be a primitive type in the JSON string but got " + data['nome']);
        }
        // ensure the json data is a string
        if (data['cpf'] && !(typeof data['cpf'] === 'string' || data['cpf'] instanceof String)) {
            throw new Error("Expected the field `cpf` to be a primitive type in the JSON string but got " + data['cpf']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        if (data['atendimentos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['atendimentos'])) {
                throw new Error("Expected the field `atendimentos` to be an array in the JSON data but got " + data['atendimentos']);
            }
            // validate the optional field `atendimentos` (array)
            for (const item of data['atendimentos']) {
                AtendimentoDetalheResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} pacienteId
 */
PacienteDetalheResponse.prototype['pacienteId'] = undefined;

/**
 * @member {String} nome
 */
PacienteDetalheResponse.prototype['nome'] = undefined;

/**
 * @member {String} cpf
 */
PacienteDetalheResponse.prototype['cpf'] = undefined;

/**
 * @member {String} email
 */
PacienteDetalheResponse.prototype['email'] = undefined;

/**
 * @member {Array.<module:model/AtendimentoDetalheResponse>} atendimentos
 */
PacienteDetalheResponse.prototype['atendimentos'] = undefined;






export default PacienteDetalheResponse;

