/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PacienteSummaryResponse model module.
 * @module model/PacienteSummaryResponse
 * @version 1.0.0
 */
class PacienteSummaryResponse {
    /**
     * Constructs a new <code>PacienteSummaryResponse</code>.
     * @alias module:model/PacienteSummaryResponse
     */
    constructor() { 
        
        PacienteSummaryResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PacienteSummaryResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PacienteSummaryResponse} obj Optional instance to populate.
     * @return {module:model/PacienteSummaryResponse} The populated <code>PacienteSummaryResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PacienteSummaryResponse();

            if (data.hasOwnProperty('pacienteId')) {
                obj['pacienteId'] = ApiClient.convertToType(data['pacienteId'], 'String');
            }
            if (data.hasOwnProperty('nome')) {
                obj['nome'] = ApiClient.convertToType(data['nome'], 'String');
            }
            if (data.hasOwnProperty('cpf')) {
                obj['cpf'] = ApiClient.convertToType(data['cpf'], 'String');
            }
            if (data.hasOwnProperty('ultimoStatus')) {
                obj['ultimoStatus'] = ApiClient.convertToType(data['ultimoStatus'], 'String');
            }
            if (data.hasOwnProperty('ultimoAtendimento')) {
                obj['ultimoAtendimento'] = ApiClient.convertToType(data['ultimoAtendimento'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PacienteSummaryResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PacienteSummaryResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['pacienteId'] && !(typeof data['pacienteId'] === 'string' || data['pacienteId'] instanceof String)) {
            throw new Error("Expected the field `pacienteId` to be a primitive type in the JSON string but got " + data['pacienteId']);
        }
        // ensure the json data is a string
        if (data['nome'] && !(typeof data['nome'] === 'string' || data['nome'] instanceof String)) {
            throw new Error("Expected the field `nome` to be a primitive type in the JSON string but got " + data['nome']);
        }
        // ensure the json data is a string
        if (data['cpf'] && !(typeof data['cpf'] === 'string' || data['cpf'] instanceof String)) {
            throw new Error("Expected the field `cpf` to be a primitive type in the JSON string but got " + data['cpf']);
        }
        // ensure the json data is a string
        if (data['ultimoStatus'] && !(typeof data['ultimoStatus'] === 'string' || data['ultimoStatus'] instanceof String)) {
            throw new Error("Expected the field `ultimoStatus` to be a primitive type in the JSON string but got " + data['ultimoStatus']);
        }

        return true;
    }


}



/**
 * @member {String} pacienteId
 */
PacienteSummaryResponse.prototype['pacienteId'] = undefined;

/**
 * @member {String} nome
 */
PacienteSummaryResponse.prototype['nome'] = undefined;

/**
 * @member {String} cpf
 */
PacienteSummaryResponse.prototype['cpf'] = undefined;

/**
 * @member {String} ultimoStatus
 */
PacienteSummaryResponse.prototype['ultimoStatus'] = undefined;

/**
 * @member {Date} ultimoAtendimento
 */
PacienteSummaryResponse.prototype['ultimoAtendimento'] = undefined;






export default PacienteSummaryResponse;

