/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProntuarioRequest model module.
 * @module model/ProntuarioRequest
 * @version 1.0.0
 */
class ProntuarioRequest {
    /**
     * Constructs a new <code>ProntuarioRequest</code>.
     * @alias module:model/ProntuarioRequest
     * @param observacoesPsicossocias {String} 
     */
    constructor(observacoesPsicossocias) { 
        
        ProntuarioRequest.initialize(this, observacoesPsicossocias);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, observacoesPsicossocias) { 
        obj['observacoesPsicossocias'] = observacoesPsicossocias;
    }

    /**
     * Constructs a <code>ProntuarioRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProntuarioRequest} obj Optional instance to populate.
     * @return {module:model/ProntuarioRequest} The populated <code>ProntuarioRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProntuarioRequest();

            if (data.hasOwnProperty('observacoesPsicossocias')) {
                obj['observacoesPsicossocias'] = ApiClient.convertToType(data['observacoesPsicossocias'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProntuarioRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProntuarioRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProntuarioRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['observacoesPsicossocias'] && !(typeof data['observacoesPsicossocias'] === 'string' || data['observacoesPsicossocias'] instanceof String)) {
            throw new Error("Expected the field `observacoesPsicossocias` to be a primitive type in the JSON string but got " + data['observacoesPsicossocias']);
        }

        return true;
    }


}

ProntuarioRequest.RequiredProperties = ["observacoesPsicossocias"];

/**
 * @member {String} observacoesPsicossocias
 */
ProntuarioRequest.prototype['observacoesPsicossocias'] = undefined;






export default ProntuarioRequest;

