/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProntuarioResponse model module.
 * @module model/ProntuarioResponse
 * @version 1.0.0
 */
class ProntuarioResponse {
    /**
     * Constructs a new <code>ProntuarioResponse</code>.
     * @alias module:model/ProntuarioResponse
     */
    constructor() { 
        
        ProntuarioResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProntuarioResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProntuarioResponse} obj Optional instance to populate.
     * @return {module:model/ProntuarioResponse} The populated <code>ProntuarioResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProntuarioResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('agendamentoId')) {
                obj['agendamentoId'] = ApiClient.convertToType(data['agendamentoId'], 'String');
            }
            if (data.hasOwnProperty('pacienteNome')) {
                obj['pacienteNome'] = ApiClient.convertToType(data['pacienteNome'], 'String');
            }
            if (data.hasOwnProperty('observacoesPsicossociais')) {
                obj['observacoesPsicossociais'] = ApiClient.convertToType(data['observacoesPsicossociais'], 'String');
            }
            if (data.hasOwnProperty('criadoPor')) {
                obj['criadoPor'] = ApiClient.convertToType(data['criadoPor'], 'String');
            }
            if (data.hasOwnProperty('criadoEm')) {
                obj['criadoEm'] = ApiClient.convertToType(data['criadoEm'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProntuarioResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProntuarioResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['agendamentoId'] && !(typeof data['agendamentoId'] === 'string' || data['agendamentoId'] instanceof String)) {
            throw new Error("Expected the field `agendamentoId` to be a primitive type in the JSON string but got " + data['agendamentoId']);
        }
        // ensure the json data is a string
        if (data['pacienteNome'] && !(typeof data['pacienteNome'] === 'string' || data['pacienteNome'] instanceof String)) {
            throw new Error("Expected the field `pacienteNome` to be a primitive type in the JSON string but got " + data['pacienteNome']);
        }
        // ensure the json data is a string
        if (data['observacoesPsicossociais'] && !(typeof data['observacoesPsicossociais'] === 'string' || data['observacoesPsicossociais'] instanceof String)) {
            throw new Error("Expected the field `observacoesPsicossociais` to be a primitive type in the JSON string but got " + data['observacoesPsicossociais']);
        }
        // ensure the json data is a string
        if (data['criadoPor'] && !(typeof data['criadoPor'] === 'string' || data['criadoPor'] instanceof String)) {
            throw new Error("Expected the field `criadoPor` to be a primitive type in the JSON string but got " + data['criadoPor']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ProntuarioResponse.prototype['id'] = undefined;

/**
 * @member {String} agendamentoId
 */
ProntuarioResponse.prototype['agendamentoId'] = undefined;

/**
 * @member {String} pacienteNome
 */
ProntuarioResponse.prototype['pacienteNome'] = undefined;

/**
 * @member {String} observacoesPsicossociais
 */
ProntuarioResponse.prototype['observacoesPsicossociais'] = undefined;

/**
 * @member {String} criadoPor
 */
ProntuarioResponse.prototype['criadoPor'] = undefined;

/**
 * @member {Date} criadoEm
 */
ProntuarioResponse.prototype['criadoEm'] = undefined;






export default ProntuarioResponse;

