/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TimelineEventoResponse model module.
 * @module model/TimelineEventoResponse
 * @version 1.0.0
 */
class TimelineEventoResponse {
    /**
     * Constructs a new <code>TimelineEventoResponse</code>.
     * @alias module:model/TimelineEventoResponse
     */
    constructor() { 
        
        TimelineEventoResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TimelineEventoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimelineEventoResponse} obj Optional instance to populate.
     * @return {module:model/TimelineEventoResponse} The populated <code>TimelineEventoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimelineEventoResponse();

            if (data.hasOwnProperty('evento')) {
                obj['evento'] = ApiClient.convertToType(data['evento'], 'String');
            }
            if (data.hasOwnProperty('descricao')) {
                obj['descricao'] = ApiClient.convertToType(data['descricao'], 'String');
            }
            if (data.hasOwnProperty('responsavel')) {
                obj['responsavel'] = ApiClient.convertToType(data['responsavel'], 'String');
            }
            if (data.hasOwnProperty('criadoEm')) {
                obj['criadoEm'] = ApiClient.convertToType(data['criadoEm'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TimelineEventoResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TimelineEventoResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['evento'] && !(typeof data['evento'] === 'string' || data['evento'] instanceof String)) {
            throw new Error("Expected the field `evento` to be a primitive type in the JSON string but got " + data['evento']);
        }
        // ensure the json data is a string
        if (data['descricao'] && !(typeof data['descricao'] === 'string' || data['descricao'] instanceof String)) {
            throw new Error("Expected the field `descricao` to be a primitive type in the JSON string but got " + data['descricao']);
        }
        // ensure the json data is a string
        if (data['responsavel'] && !(typeof data['responsavel'] === 'string' || data['responsavel'] instanceof String)) {
            throw new Error("Expected the field `responsavel` to be a primitive type in the JSON string but got " + data['responsavel']);
        }

        return true;
    }


}



/**
 * @member {String} evento
 */
TimelineEventoResponse.prototype['evento'] = undefined;

/**
 * @member {String} descricao
 */
TimelineEventoResponse.prototype['descricao'] = undefined;

/**
 * @member {String} responsavel
 */
TimelineEventoResponse.prototype['responsavel'] = undefined;

/**
 * @member {Date} criadoEm
 */
TimelineEventoResponse.prototype['criadoEm'] = undefined;






export default TimelineEventoResponse;

