/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ViolenciaRequest model module.
 * @module model/ViolenciaRequest
 * @version 1.0.0
 */
class ViolenciaRequest {
    /**
     * Constructs a new <code>ViolenciaRequest</code>.
     * @alias module:model/ViolenciaRequest
     * @param violencia {String} 
     */
    constructor(violencia) { 
        
        ViolenciaRequest.initialize(this, violencia);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, violencia) { 
        obj['violencia'] = violencia;
    }

    /**
     * Constructs a <code>ViolenciaRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ViolenciaRequest} obj Optional instance to populate.
     * @return {module:model/ViolenciaRequest} The populated <code>ViolenciaRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ViolenciaRequest();

            if (data.hasOwnProperty('violencia')) {
                obj['violencia'] = ApiClient.convertToType(data['violencia'], 'String');
            }
            if (data.hasOwnProperty('violenciaOutro')) {
                obj['violenciaOutro'] = ApiClient.convertToType(data['violenciaOutro'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ViolenciaRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ViolenciaRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ViolenciaRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['violencia'] && !(typeof data['violencia'] === 'string' || data['violencia'] instanceof String)) {
            throw new Error("Expected the field `violencia` to be a primitive type in the JSON string but got " + data['violencia']);
        }
        // ensure the json data is a string
        if (data['violenciaOutro'] && !(typeof data['violenciaOutro'] === 'string' || data['violenciaOutro'] instanceof String)) {
            throw new Error("Expected the field `violenciaOutro` to be a primitive type in the JSON string but got " + data['violenciaOutro']);
        }

        return true;
    }


}

ViolenciaRequest.RequiredProperties = ["violencia"];

/**
 * @member {String} violencia
 */
ViolenciaRequest.prototype['violencia'] = undefined;

/**
 * @member {String} violenciaOutro
 */
ViolenciaRequest.prototype['violenciaOutro'] = undefined;






export default ViolenciaRequest;

