/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VolumeDiarioResponse model module.
 * @module model/VolumeDiarioResponse
 * @version 1.0.0
 */
class VolumeDiarioResponse {
    /**
     * Constructs a new <code>VolumeDiarioResponse</code>.
     * @alias module:model/VolumeDiarioResponse
     */
    constructor() { 
        
        VolumeDiarioResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VolumeDiarioResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VolumeDiarioResponse} obj Optional instance to populate.
     * @return {module:model/VolumeDiarioResponse} The populated <code>VolumeDiarioResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VolumeDiarioResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'Date');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VolumeDiarioResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VolumeDiarioResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Date} data
 */
VolumeDiarioResponse.prototype['data'] = undefined;

/**
 * @member {Number} total
 */
VolumeDiarioResponse.prototype['total'] = undefined;






export default VolumeDiarioResponse;

