/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalaLilsApi);
  }
}(this, function(expect, SalaLilsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalaLilsApi.AnamneseInicialRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AnamneseInicialRequest', function() {
    it('should create an instance of AnamneseInicialRequest', function() {
      // uncomment below and update the code to test AnamneseInicialRequest
      //var instance = new SalaLilsApi.AnamneseInicialRequest();
      //expect(instance).to.be.a(SalaLilsApi.AnamneseInicialRequest);
    });

    it('should have the property tipoAtendimento (base name: "tipoAtendimento")', function() {
      // uncomment below and update the code to test the property tipoAtendimento
      //var instance = new SalaLilsApi.AnamneseInicialRequest();
      //expect(instance).to.be();
    });

    it('should have the property primeiroAtendimento (base name: "primeiroAtendimento")', function() {
      // uncomment below and update the code to test the property primeiroAtendimento
      //var instance = new SalaLilsApi.AnamneseInicialRequest();
      //expect(instance).to.be();
    });

    it('should have the property territorio (base name: "territorio")', function() {
      // uncomment below and update the code to test the property territorio
      //var instance = new SalaLilsApi.AnamneseInicialRequest();
      //expect(instance).to.be();
    });

    it('should have the property corRaca (base name: "corRaca")', function() {
      // uncomment below and update the code to test the property corRaca
      //var instance = new SalaLilsApi.AnamneseInicialRequest();
      //expect(instance).to.be();
    });

    it('should have the property sexoGenero (base name: "sexoGenero")', function() {
      // uncomment below and update the code to test the property sexoGenero
      //var instance = new SalaLilsApi.AnamneseInicialRequest();
      //expect(instance).to.be();
    });

    it('should have the property sexoGeneroOutro (base name: "sexoGeneroOutro")', function() {
      // uncomment below and update the code to test the property sexoGeneroOutro
      //var instance = new SalaLilsApi.AnamneseInicialRequest();
      //expect(instance).to.be();
    });

    it('should have the property violencias (base name: "violencias")', function() {
      // uncomment below and update the code to test the property violencias
      //var instance = new SalaLilsApi.AnamneseInicialRequest();
      //expect(instance).to.be();
    });

  });

}));
