/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalaLilsApi);
  }
}(this, function(expect, SalaLilsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalaLilsApi.AnamneseTecnicaRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AnamneseTecnicaRequest', function() {
    it('should create an instance of AnamneseTecnicaRequest', function() {
      // uncomment below and update the code to test AnamneseTecnicaRequest
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be.a(SalaLilsApi.AnamneseTecnicaRequest);
    });

    it('should have the property riscoIminente (base name: "riscoIminente")', function() {
      // uncomment below and update the code to test the property riscoIminente
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property agressorConvive (base name: "agressorConvive")', function() {
      // uncomment below and update the code to test the property agressorConvive
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property historicoViolencia (base name: "historicoViolencia")', function() {
      // uncomment below and update the code to test the property historicoViolencia
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property redeApoio (base name: "redeApoio")', function() {
      // uncomment below and update the code to test the property redeApoio
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property filhosDependentes (base name: "filhosDependentes")', function() {
      // uncomment below and update the code to test the property filhosDependentes
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property observacoes (base name: "observacoes")', function() {
      // uncomment below and update the code to test the property observacoes
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property registroAtendimento (base name: "registroAtendimento")', function() {
      // uncomment below and update the code to test the property registroAtendimento
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property detalhamentoEncaminhamentos (base name: "detalhamentoEncaminhamentos")', function() {
      // uncomment below and update the code to test the property detalhamentoEncaminhamentos
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property planoAcompanhamento (base name: "planoAcompanhamento")', function() {
      // uncomment below and update the code to test the property planoAcompanhamento
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property dataRetorno (base name: "dataRetorno")', function() {
      // uncomment below and update the code to test the property dataRetorno
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property planoObservacoes (base name: "planoObservacoes")', function() {
      // uncomment below and update the code to test the property planoObservacoes
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property sinteseCaso (base name: "sinteseCaso")', function() {
      // uncomment below and update the code to test the property sinteseCaso
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property orientacoes (base name: "orientacoes")', function() {
      // uncomment below and update the code to test the property orientacoes
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property encaminhamentos (base name: "encaminhamentos")', function() {
      // uncomment below and update the code to test the property encaminhamentos
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

    it('should have the property objetivos (base name: "objetivos")', function() {
      // uncomment below and update the code to test the property objetivos
      //var instance = new SalaLilsApi.AnamneseTecnicaRequest();
      //expect(instance).to.be();
    });

  });

}));
