/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalaLilsApi);
  }
}(this, function(expect, SalaLilsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalaLilsApi.AtendimentoRelatorioResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AtendimentoRelatorioResponse', function() {
    it('should create an instance of AtendimentoRelatorioResponse', function() {
      // uncomment below and update the code to test AtendimentoRelatorioResponse
      //var instance = new SalaLilsApi.AtendimentoRelatorioResponse();
      //expect(instance).to.be.a(SalaLilsApi.AtendimentoRelatorioResponse);
    });

    it('should have the property agendamentoId (base name: "agendamentoId")', function() {
      // uncomment below and update the code to test the property agendamentoId
      //var instance = new SalaLilsApi.AtendimentoRelatorioResponse();
      //expect(instance).to.be();
    });

    it('should have the property pacienteNome (base name: "pacienteNome")', function() {
      // uncomment below and update the code to test the property pacienteNome
      //var instance = new SalaLilsApi.AtendimentoRelatorioResponse();
      //expect(instance).to.be();
    });

    it('should have the property data (base name: "data")', function() {
      // uncomment below and update the code to test the property data
      //var instance = new SalaLilsApi.AtendimentoRelatorioResponse();
      //expect(instance).to.be();
    });

    it('should have the property horario (base name: "horario")', function() {
      // uncomment below and update the code to test the property horario
      //var instance = new SalaLilsApi.AtendimentoRelatorioResponse();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new SalaLilsApi.AtendimentoRelatorioResponse();
      //expect(instance).to.be();
    });

    it('should have the property atendente (base name: "atendente")', function() {
      // uncomment below and update the code to test the property atendente
      //var instance = new SalaLilsApi.AtendimentoRelatorioResponse();
      //expect(instance).to.be();
    });

    it('should have the property criadoEm (base name: "criadoEm")', function() {
      // uncomment below and update the code to test the property criadoEm
      //var instance = new SalaLilsApi.AtendimentoRelatorioResponse();
      //expect(instance).to.be();
    });

  });

}));
