/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalaLilsApi);
  }
}(this, function(expect, SalaLilsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalaLilsApi.ContadoresResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContadoresResponse', function() {
    it('should create an instance of ContadoresResponse', function() {
      // uncomment below and update the code to test ContadoresResponse
      //var instance = new SalaLilsApi.ContadoresResponse();
      //expect(instance).to.be.a(SalaLilsApi.ContadoresResponse);
    });

    it('should have the property aguardando (base name: "aguardando")', function() {
      // uncomment below and update the code to test the property aguardando
      //var instance = new SalaLilsApi.ContadoresResponse();
      //expect(instance).to.be();
    });

    it('should have the property emAtendimento (base name: "emAtendimento")', function() {
      // uncomment below and update the code to test the property emAtendimento
      //var instance = new SalaLilsApi.ContadoresResponse();
      //expect(instance).to.be();
    });

  });

}));
