/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalaLilsApi);
  }
}(this, function(expect, SalaLilsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalaLilsApi.LoginResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoginResponse', function() {
    it('should create an instance of LoginResponse', function() {
      // uncomment below and update the code to test LoginResponse
      //var instance = new SalaLilsApi.LoginResponse();
      //expect(instance).to.be.a(SalaLilsApi.LoginResponse);
    });

    it('should have the property accessToken (base name: "accessToken")', function() {
      // uncomment below and update the code to test the property accessToken
      //var instance = new SalaLilsApi.LoginResponse();
      //expect(instance).to.be();
    });

    it('should have the property refreshToken (base name: "refreshToken")', function() {
      // uncomment below and update the code to test the property refreshToken
      //var instance = new SalaLilsApi.LoginResponse();
      //expect(instance).to.be();
    });

    it('should have the property perfil (base name: "perfil")', function() {
      // uncomment below and update the code to test the property perfil
      //var instance = new SalaLilsApi.LoginResponse();
      //expect(instance).to.be();
    });

    it('should have the property lgpdPendente (base name: "lgpdPendente")', function() {
      // uncomment below and update the code to test the property lgpdPendente
      //var instance = new SalaLilsApi.LoginResponse();
      //expect(instance).to.be();
    });

  });

}));
