/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalaLilsApi);
  }
}(this, function(expect, SalaLilsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalaLilsApi.MeResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MeResponse', function() {
    it('should create an instance of MeResponse', function() {
      // uncomment below and update the code to test MeResponse
      //var instance = new SalaLilsApi.MeResponse();
      //expect(instance).to.be.a(SalaLilsApi.MeResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SalaLilsApi.MeResponse();
      //expect(instance).to.be();
    });

    it('should have the property nome (base name: "nome")', function() {
      // uncomment below and update the code to test the property nome
      //var instance = new SalaLilsApi.MeResponse();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new SalaLilsApi.MeResponse();
      //expect(instance).to.be();
    });

    it('should have the property perfil (base name: "perfil")', function() {
      // uncomment below and update the code to test the property perfil
      //var instance = new SalaLilsApi.MeResponse();
      //expect(instance).to.be();
    });

    it('should have the property lgpdAceito (base name: "lgpdAceito")', function() {
      // uncomment below and update the code to test the property lgpdAceito
      //var instance = new SalaLilsApi.MeResponse();
      //expect(instance).to.be();
    });

    it('should have the property lgpdData (base name: "lgpdData")', function() {
      // uncomment below and update the code to test the property lgpdData
      //var instance = new SalaLilsApi.MeResponse();
      //expect(instance).to.be();
    });

  });

}));
