/**
 * Sala Lilás API
 * Sistema de atendimento Sala Lilás
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalaLilsApi);
  }
}(this, function(expect, SalaLilsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalaLilsApi.PacienteSummaryResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PacienteSummaryResponse', function() {
    it('should create an instance of PacienteSummaryResponse', function() {
      // uncomment below and update the code to test PacienteSummaryResponse
      //var instance = new SalaLilsApi.PacienteSummaryResponse();
      //expect(instance).to.be.a(SalaLilsApi.PacienteSummaryResponse);
    });

    it('should have the property pacienteId (base name: "pacienteId")', function() {
      // uncomment below and update the code to test the property pacienteId
      //var instance = new SalaLilsApi.PacienteSummaryResponse();
      //expect(instance).to.be();
    });

    it('should have the property nome (base name: "nome")', function() {
      // uncomment below and update the code to test the property nome
      //var instance = new SalaLilsApi.PacienteSummaryResponse();
      //expect(instance).to.be();
    });

    it('should have the property cpf (base name: "cpf")', function() {
      // uncomment below and update the code to test the property cpf
      //var instance = new SalaLilsApi.PacienteSummaryResponse();
      //expect(instance).to.be();
    });

    it('should have the property ultimoStatus (base name: "ultimoStatus")', function() {
      // uncomment below and update the code to test the property ultimoStatus
      //var instance = new SalaLilsApi.PacienteSummaryResponse();
      //expect(instance).to.be();
    });

    it('should have the property ultimoAtendimento (base name: "ultimoAtendimento")', function() {
      // uncomment below and update the code to test the property ultimoAtendimento
      //var instance = new SalaLilsApi.PacienteSummaryResponse();
      //expect(instance).to.be();
    });

  });

}));
